Repository istio/operator, pull requests merged in 2019-12, with the labels that each got.

#648 common-files update master-2019-11-26T07-29-27
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#636 [release-1.4] sync values types
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/L

#647 validation should fail for yaml with no spec
  pkg/manifest/installer.go
Labels: cla: yes, size/XS

#650 This introduces the latest installer.sha
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#646 Disable leader election when LEADER_ELECTION_NAMESPACE is not set
  cmd/manager/server.go
Labels: cla: yes, ok-to-test, size/S

#649 Fix logging and vfs filepath for windows
  cmd/mesh/shared.go
  pkg/helm/vfs_renderer.go
  pkg/helm/vfs_renderer_test.go
Labels: cla: yes, size/M

#651 [release-1.4] Fix logging and vfs filepath for windows
  cmd/mesh/shared.go
  pkg/helm/vfs_renderer.go
  pkg/helm/vfs_renderer_test.go
Labels: cla: yes, size/M

#653 Fix windows yaml generation
  pkg/helm/vfs_renderer.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#654 [release-1.4] Fix windows yaml generation
  pkg/helm/vfs_renderer.go
Labels: cla: yes, size/XS

#657 Sync installer sha
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#652 Read ICP only from the local cache
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
Labels: cla: yes, ok-to-test, size/M

#659 Use a set to simplify handling of finalizers & fix potential panic
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
Labels: cla: yes, ok-to-test, size/M

#643 Operator init and remove commands
  cmd/mesh/manifest-common.go
  cmd/mesh/manifest-migrate.go
  cmd/mesh/operator-common.go
  cmd/mesh/operator-init.go
  cmd/mesh/operator-remove.go
  cmd/mesh/operator.go
  cmd/mesh/operator_test.go
  cmd/mesh/root.go
  cmd/mesh/shared.go
  cmd/mesh/testdata/operator/output/operator-init.yaml
  cmd/mesh/testdata/operator/output/operator-remove.yaml
  data/operator/Chart.yaml
  data/operator/templates/clusterrole.yaml
  data/operator/templates/clusterrole_binding.yaml
  data/operator/templates/crd.yaml
  data/operator/templates/deployment.yaml
  data/operator/templates/namespace.yaml
  data/operator/templates/service.yaml
  data/operator/templates/service_account.yaml
  go.sum
  pkg/kubectlcmd/client.go
  pkg/kubectlcmd/client_test.go
  pkg/manifest/installer.go
  pkg/name/name.go
  pkg/translate/translate.go
  pkg/translate/translate_value.go
  pkg/util/util.go
  pkg/vfs/assets.gen.go
  samples/default-install.yaml
Labels: cla: yes, size/XXL

#660 Fix reconcile conflict error
  pkg/controller/istiocontrolplane/listeners.go
Labels: cla: yes, size/S

#658 Add base feature and component and empty profile
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/examples/user-gateway/ingress-gateway-only.yaml
  data/profiles/default.yaml
  data/profiles/empty.yaml
  data/translateConfig/translateConfig-1.4.yaml
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/L

#661 [release-1.4] Fix reconcile conflict error
  pkg/controller/istiocontrolplane/listeners.go
Labels: cla: yes, size/S

#662 [release-1.4] Update installer #587 SHA
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
  tests/profiles/helm/values-istio-minimal.yaml
Labels: cla: yes, size/XXL

#663 Add Google CA values
  data/examples/googleca/values-istio-google-ca.yaml
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#666 [release-1.4] Add Google CA values (#663)
  data/examples/googleca/values-istio-google-ca.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#665 Fix minimal values-test file
  tests/profiles/helm/values-istio-minimal.yaml
Labels: cla: yes, size/XS

#668 Fix parse objects from yaml
  pkg/object/objects.go
Labels: cherrypick/release-1.4, cla: yes

#669 [release-1.4] Fix parse objects from yaml
  pkg/object/objects.go
Labels: cla: yes, size/XS

#673 [release-1.4]sync with installer(telemetry v2 change)
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/M

#675 Add nil check when determining reflect.Kind of types
  pkg/patch/patch.go
  pkg/patch/patch_test.go
  pkg/util/reflect.go
Labels: cla: yes, ok-to-test, size/M

#672 Re-apply the partially reverted output improvements from PR#625
  cmd/mesh/manifest-common.go
  cmd/mesh/manifest-generate.go
Labels: cla: yes, size/M

#676 [release-1.4] Re-apply the partially reverted output improvements from PR#625 (#672)
  cmd/mesh/manifest-common.go
  cmd/mesh/manifest-generate.go
Labels: cla: yes, size/M

#681 Profile set with flag should have highest priority
  cmd/mesh/profile-common.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#682 [release-1.4] Profile set with flag should have highest priority
  cmd/mesh/profile-common.go
Labels: cla: yes, size/XS

#683 Simplify outputs, hide component details if no errors.
  cmd/mesh/manifest-common.go
  pkg/manifest/installer.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#679 Fix a concurrency issue by not sharing the same kubectl.opts object i…
  cmd/mesh/operator-init.go
  pkg/manifest/installer.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#684 [release-1.4] Simplify outputs, hide component detail results if no errors. (#683)
  cmd/mesh/manifest-common.go
  pkg/manifest/installer.go
Labels: cla: yes, size/M

#678 Update values
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/M

#686 [release-1.4] update to latest installer sha
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#685 update(installer): use latest sha for telemetry v2 and owners fix
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/operator/output/operator-init.yaml
  cmd/mesh/testdata/operator/output/operator-remove.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XL

#687 Add messages for pruning disabled objects.
  pkg/manifest/installer.go
Labels: cla: yes, size/XS

#671 upgrade cmd: using ICPS to compare changes between current install and target install.
  cmd/mesh/manifest-common.go
  cmd/mesh/manifest-generate_test.go
  cmd/mesh/profile-common.go
  cmd/mesh/upgrade.go
  pkg/helm/urlfetcher.go
  pkg/hooks/upgrade_hooks.go
Labels: cherrypick/release-1.4, cla: yes, size/L

#674 watch Istio resources changes in istio-operator
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go
  pkg/helmreconciler/reconciler.go
  pkg/helmreconciler/rendering.go
  tests/e2e/e2e.sh
Labels: cla: yes, size/L

#688 Fix scripts to not hardcode istio/installer
  Makefile.core.mk
  release/create_release_charts.sh
  scripts/run_update_charts.sh
Labels: cherrypick/release-1.4, cla: yes, size/M

#691 [release-1.4] Fix scripts to not hardcode istio/installer
  Makefile.core.mk
  release/create_release_charts.sh
  scripts/run_update_charts.sh
Labels: cla: yes, size/M

#690 Fix affinity translation
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#689 Logtostderr should actually go to stderr
  cmd/mesh/shared.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#692 [release-1.4] Logtostderr should actually go to stderr
  cmd/mesh/shared.go
Labels: cla: yes, size/XS

#693 Fix manifest diff output
  cmd/mesh/manifest-diff.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#697 Add a validation function to check global.mtls.auto && !global.controlPlaneSecurity
  pkg/apis/istio/v1alpha2/validation/validation.go
  pkg/apis/istio/v1alpha2/validation/validation_test.go
Labels: cla: yes, size/M

#695 [release-1.4] Fix affinity translation (#690)
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  data/translateConfig/translateConfig-1.4.yaml
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#702 Update installer SHA
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#703 common-files update master-2019-12-15T16-17-48
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#704 Update the version/versions.yaml
  version/versions.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#705 [release-1.4] Update the version/versions.yaml
  version/versions.yaml
Labels: cla: yes, size/S

#698 Upgrade libraries to Kubernetes 1.17
  go.mod
  go.sum
  licenses/github.com/Azure/go-autorest/autorest/LICENSE
  licenses/github.com/Azure/go-autorest/autorest/adal/LICENSE
  licenses/github.com/Azure/go-autorest/autorest/date/LICENSE
  licenses/github.com/Azure/go-autorest/autorest/mocks/LICENSE
  licenses/github.com/Azure/go-autorest/logger/LICENSE
  licenses/github.com/Azure/go-autorest/tracing/LICENSE
  licenses/github.com/agnivade/levenshtein/License.txt
  licenses/github.com/andreyvit/diff/LICENSE
  licenses/github.com/bgentry/speakeasy/LICENSE
  licenses/github.com/cockroachdb/datadriven/LICENSE
  licenses/github.com/creack/pty/LICENSE
  licenses/github.com/dustin/go-humanize/LICENSE
  licenses/github.com/fatih/color/LICENSE.md
  licenses/github.com/mattn/go-colorable/LICENSE
  licenses/github.com/mattn/go-isatty/LICENSE
  licenses/github.com/mattn/go-runewidth/LICENSE
  licenses/github.com/munnerz/goautoneg/LICENSE
  licenses/github.com/munnerz/goautoneg/NONE
  licenses/github.com/olekukonko/tablewriter/LICENCE.md
  licenses/github.com/sergi/go-diff/LICENSE
  licenses/github.com/tidwall/pretty/LICENSE
  licenses/github.com/urfave/cli/LICENSE
  licenses/github.com/vektah/gqlparser/LICENSE
  licenses/github.com/vektah/gqlparser/validator/imported/LICENSE
  licenses/github.com/xlab/handysort/LICENSE
  licenses/go.etcd.io/bbolt/LICENSE
  licenses/go.etcd.io/etcd/LICENSE
  licenses/go.mongodb.org/mongo-driver/LICENSE
  licenses/golang.org/x/xerrors/LICENSE
  licenses/gopkg.in/cheggaaa/pb.v1/LICENSE
  licenses/gopkg.in/yaml.v1/LICENSE
  licenses/vbom.ml/util/LICENSE
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/controller/istiocontrolplane/pruningdetails.go
Labels: cla: yes, size/XXL

#677 Update the version of operator for 1.4.3
  cmd/mesh/manifest-versions.go
  cmd/mesh/manifest-versions_test.go
  cmd/mesh/testdata/manifest-versions/input/versions.yaml
  data/versions.yaml
  pkg/version/version.go
  pkg/version/version_test.go
  pkg/vfs/assets.gen.go
  release/create_release_charts.sh
  version/version.go
  version/versions.yaml
Labels: cherrypick/release-1.4, cla: yes, size/L

#706 [release-1.4] Update the version of operator for 1.4.3
  cmd/mesh/manifest-versions.go
  cmd/mesh/manifest-versions_test.go
  cmd/mesh/testdata/manifest-versions/input/versions.yaml
  data/versions.yaml
  pkg/version/version.go
  pkg/version/version_test.go
  pkg/vfs/assets.gen.go
  release/create_release_charts.sh
  version/version.go
  version/versions.yaml
Labels: cla: yes, size/L

#696 migrate logic and output update
  cmd/mesh/manifest-migrate.go
  cmd/mesh/manifest-migrate_test.go
  cmd/mesh/testdata/manifest-migrate/input/default_values.yaml
  cmd/mesh/testdata/manifest-migrate/input/overlay_values.yaml
  cmd/mesh/testdata/manifest-migrate/output/default_values.yaml
  cmd/mesh/testdata/manifest-migrate/output/overlay_values.yaml
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/name/name.go
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/L

#707 Fallback to previous versions when failing to create translator
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
Labels: cla: yes, size/L

#680 add tolerations to schema
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/S

#714 sync values types with release-1.4
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/M

#715 [Release-1.4] update migrate and sync values types
  cmd/mesh/manifest-migrate.go
  cmd/mesh/manifest-migrate_test.go
  cmd/mesh/testdata/manifest-migrate/input/default_values.yaml
  cmd/mesh/testdata/manifest-migrate/input/overlay_values.yaml
  cmd/mesh/testdata/manifest-migrate/output/default_values.yaml
  cmd/mesh/testdata/manifest-migrate/output/overlay_values.yaml
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/name/name.go
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/L

#717 Sync installer
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
  scripts/run_mandiff.sh
Labels: cla: yes, size/XXL

#716 fix invalid version format from docker build info.
  version/version.go
Labels: cla: yes, size/XS

#710 Update operator version to 1.5.0; support setting version by BuildInfo Tag.
  data/versions.yaml
  pkg/version/version.go
  pkg/version/version_test.go
  pkg/vfs/assets.gen.go
  version/version.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#721 Fixed 19747
  cmd/mesh/manifest-common.go
Labels: cla: yes, size/XS

#722 mesh profile diff should not output usage info when diff is found.
  cmd/mesh/profile-diff.go
Labels: cla: yes, size/XS

#723 [release-1.4] Fixed 19747
  cmd/mesh/manifest-common.go
Labels: cla: yes, size/XS

#709 [release-1.4] Fallback to previous versions when failing to create translator
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
Labels: cla: yes, size/L

#720 [release-1.4] fix invalid version format from docker build info.
  version/version.go
Labels: cla: yes, size/XS

#725 Fix --wait in manifest apply not being used.
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-common.go
  cmd/mesh/upgrade.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#719 Add TODO comments of version 1.5 for translate
  pkg/translate/translate_test.go
  pkg/translate/translate_value_test.go
Labels: cla: yes, size/S
