Repository istio/operator, pull requests merged in 2019-10, with the labels that each got.

#305 update versions map.
  cmd/mesh/manifest-versions.go
  version/versions.yaml
Labels: cla: yes, size/XS

#309 Fix build issue.
  Makefile.core.mk
  common-protos/.commonfiles.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#313 Run go mod tidy and add to make target
  Makefile.core.mk
  go.sum
Labels: cla: yes, size/M

#312 Update golden files
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  pkg/translate/translate_test.go
  pkg/translate/translate_value_test.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#314 Add a gen-check target.
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
Labels: cla: yes, size/M

#316 Fix the gen-check target.
  Makefile
  Makefile.core.mk
  common-protos/.commonfiles.sha
  common/.commonfiles.sha
  common/Makefile.common.mk
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#318 Makefile fixes.
  Makefile.core.mk
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#320 Fix comment formatting so it renders correctly in HTML.
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cla: yes, size/L

#301 Integrate v1alpha2 helm renderer with controller framework
  README.md
  go.mod
  go.sum
  pkg/apis/addtoscheme_istio_v1alpha1.go
  pkg/apis/istio/v1alpha1/doc.go
  pkg/apis/istio/v1alpha1/istiocontrolplane_types.go
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/apis/istio/v1alpha1/zz_generated.deepcopy.gen.go
  pkg/apis/istio/v1alpha1/zz_generated.defaults.gen.go
  pkg/apis/istio/v1alpha1/zz_generated.openapi.gen.go
  pkg/apis/istio/v1alpha2/deepcopy.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/register.go
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/controller/add_istiocontrolplane.go
  pkg/controller/istiocontrolplane/args.go
  pkg/controller/istiocontrolplane/customizer.go
  pkg/controller/istiocontrolplane/inputs.go
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/controller/istiocontrolplane/listeners.go
  pkg/controller/istiocontrolplane/pruningdetails.go
  pkg/helmreconciler/dependencies.go
  pkg/helmreconciler/interfaces.go
  pkg/helmreconciler/listeners.go
  pkg/helmreconciler/pruning.go
  pkg/helmreconciler/reconciler.go
  pkg/helmreconciler/rendering.go
  pkg/translate/translate_value_test.go
  pkg/util/yaml.go
  pkg/validate/validate.go
  pkg/validate/validate_values_test.go
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cla: yes, size/XXL

#324 fix inconsistent api group.
  deploy/crds/istio_v1alpha1_istiocontrolplane_cr.yaml
  deploy/crds/istio_v1alpha1_istiocontrolplane_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  pkg/apis/istio/v1alpha2/register.go
Labels: cla: yes, size/S

#325 register istio operator v1alph2 api.
  pkg/apis/istio/v1alpha2/common.go
  pkg/apis/istio/v1alpha2/deepcopy.go
  pkg/apis/istio/v1alpha2/register.go
Labels: cla: yes, size/M

#326 Fix release script to read from installer.sha
  release/create_release_charts.sh
Labels: cla: yes, size/S

#327 Revert DeepCopy to use un/marshal
  pkg/apis/istio/v1alpha2/deepcopy.go
Labels: cla: yes, size/S

#328 Change logging to use Istio common log
  go.mod
  go.sum
  pkg/controller/add_istiocontrolplane.go
  pkg/controller/controller.go
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/controller/istiocontrolplane/listeners.go
  pkg/helmreconciler/customizers.go
  pkg/helmreconciler/listeners.go
  pkg/helmreconciler/pruning.go
  pkg/helmreconciler/reconciler.go
  pkg/helmreconciler/rendering.go
Labels: cla: yes, size/L

#307 add controller target in makefile.
  .gitignore
  Makefile.core.mk
  build/Dockerfile
  deploy/operator.yaml
Labels: cla: yes, size/S

#329 Permit overriding of the Makefile HUB and TAG
  Makefile.core.mk
  deploy/operator.yaml
Labels: cla: yes, size/XS

#321 [release-1.3] Fix comment formatting so it renders correctly in HTML.
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cla: yes, size/L

#332 update with `make vfsgen`
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#334 update build output path.
  .gitignore
  hack/sdk
Labels: cla: yes, size/XS

#335 Tweak comment to fix html generation.
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cherrypick/release-1.3, cla: yes, size/XS

#337 [release-1.3] Tweak comment to fix html generation.
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cla: yes, size/XS

#338 couple of bug fixes for controller.
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/controller/istiocontrolplane/inputs.go
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/controller/istiocontrolplane/pruningdetails.go
  pkg/helmreconciler/reconciler.go
  pkg/helmreconciler/rendering.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cla: yes, size/M

#340 Operator/common files
  Makefile
  Makefile.core.mk
  build/Dockerfile
Labels: cla: yes, size/S

#342 Update to common-files
  Makefile
  common/.commonfiles.sha
Labels: cla: yes

#343 Workaround markdown conversion bug.
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cla: yes, size/S

#341 Update installer.sha and artifacts
  Makefile.core.mk
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  installer.sha
  pkg/translate/translate.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#344 minor fixes for controller
  deploy/crds/istio_v1alpha2_istiocontrolplane_cr.yaml
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
  pkg/controller/istiocontrolplane/inputs.go
  pkg/helmreconciler/interfaces.go
Labels: cla: yes, size/XS

#346 fix status updater.
  cmd/manager/server.go
  go.mod
  go.sum
  pkg/controller/istiocontrolplane/inputs.go
  pkg/controller/istiocontrolplane/listeners.go
  pkg/helmreconciler/pruning.go
  pkg/helmreconciler/reconciler.go
  pkg/helmreconciler/rendering.go
Labels: cla: yes, size/S

#347 Fix defect in operator manifest
  deploy/operator.yaml
Labels: cla: yes, size/XS

#349 Use correct location for per commit image.
  deploy/operator.yaml
Labels: cla: yes, size/XS

#352 Run kubectl apply -k deploy to deploy operator
  deploy/kustomization.yaml
  deploy/namespace.yaml
Labels: cla: yes, size/S

#354 Set the namesapce for the istiocontrolplane CR
  deploy/crds/istio_v1alpha2_istiocontrolplane_cr.yaml
Labels: cla: yes, size/XS

#357 Set EnumsAsInts as True for jsonpb
  pkg/util/yaml.go
Labels: cla: yes, size/XS

#345 Set Owner info for Istio Objects
  pkg/controller/istiocontrolplane/pruningdetails.go
  pkg/helmreconciler/listeners.go
  pkg/util/common.go
Labels: cla: yes, size/S

#356 update rbac
  deploy/clusterrole.yaml
  deploy/clusterrole_binding.yaml
  deploy/kustomization.yaml
Labels: cla: yes, size/S

#358 Fix Concurrent Error
  pkg/helmreconciler/reconciler.go
Labels: cla: yes, size/S

#351 Drop direct usages of k8s.io/kubernetes
  go.mod
  go.sum
  pkg/helmreconciler/patching.go
  pkg/helmreconciler/rendering.go
  pkg/manifest/installer.go
Labels: cla: yes, size/L

#359 watch all namespaces.
  deploy/operator.yaml
Labels: cla: yes, size/XS

#350 Trim dependencies on kubernetes
  Makefile.core.mk
  cmd/manager/server.go
  deploy/kustomization.yaml
  deploy/service.yaml
  go.mod
  go.sum
Labels: cla: yes, size/L

#361 Update common files.
  .gitignore
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cla: yes, size/M

#363 Trim go-autorest dependency
  go.mod
  go.sum
Labels: cla: yes, size/S

#364 Switch to WithoutConversionCodecFactory to support k8s 1.16
  pkg/manifest/installer.go
Labels: cla: yes, size/XS

#323 Remove extra quotes from CONTAINER_OPTIONS
  Makefile.overrides.mk
Labels: cla: yes, size/XS

#362 minor updates to README
  README.md
Labels: cla: yes, size/XS

#365 Enable all clusterroles needed by operator
  deploy/clusterrole.yaml
Labels: cla: yes, size/M

#366 Fix mutating webhook configuraiton in cluster role
  deploy/clusterrole.yaml
Labels: cla: yes, size/XS

#371 Fix DeadLock problem for reconciler
  pkg/controller/istiocontrolplane/inputs.go
Labels: cla: yes, size/S

#373 add leader election namespace.
  cmd/manager/server.go
  deploy/operator.yaml
Labels: cla: yes, size/S

#360 batch of fixes for the controller.
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/helmreconciler/listeners.go
Labels: cla: yes, size/S

#374 Set namespace in objects
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
  deploy/operator.yaml
  deploy/service.yaml
  deploy/service_account.yaml
Labels: cla: yes, size/XS

#376 Remove namespace from CRD.
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
Labels: cla: yes, size/XS

#377 Update common files
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#378 Fix NPE
  pkg/helmreconciler/rendering.go
Labels: cla: yes, size/XS

#331 Add a docker.save target
  Makefile.core.mk
Labels: cla: yes, size/XS

#369 Add readme for testing controller
  pkg/controller/README.md
Labels: cla: yes, size/S

#303 Support --set profile=x
  cmd/mesh/manifest-generate_test.go
  cmd/mesh/profile-dump.go
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
Labels: cla: yes, size/XXL

#380 Test Switch Profile for IstioControlPlane via controller
  pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go
Labels: cla: yes, size/L

#355 Add --prune back to manifest apply kubectl command
  pkg/manifest/installer.go
Labels: cla: yes, size/XS

#370 Add anonymous synthetic types for Go struct generation
  Makefile.core.mk
  pkg/apis/istio/fixup_structs/main.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cla: yes, size/M

#381 fix istiocontrolplane cr deletion.
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
Labels: cla: yes, size/S

#383 Turn on values validation and update values schema
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/util/yaml.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
  pkg/validate/validate_values_test.go
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/XXL

#385 Add package for upgrade hooks
  pkg/hooks/upgrade_hooks.go
  pkg/hooks/upgrade_hooks_test.go
Labels: cla: yes, size/L

#386 fix fields order in istiocontrolplane.
  pkg/apis/istio/fixup_structs/main.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cla: yes, size/XS

#387 Add more switch Profile Test
  pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go
Labels: cla: yes, size/L

#388 fix istio prune issues.
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/controller/istiocontrolplane/pruningdetails.go
Labels: cla: yes, size/XS

#393 Add script to generate migrated profile from installer
  scripts/run_migrate_profile.sh
Labels: cla: yes, size/M

#348 istioctl x upgrade
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest-versions.go
  cmd/mesh/manifest.go
  cmd/mesh/profile-dump.go
  cmd/mesh/root.go
  cmd/mesh/shared.go
  cmd/mesh/upgrade-hooks.go
  cmd/mesh/upgrade.go
  data/translateConfig/translateConfig-1.4.yaml
  go.mod
  go.sum
  pkg/manifest/client.go
  pkg/manifest/installer.go
  pkg/vfs/assets.gen.go
  version/version.go
  version/versions.yaml
Labels: cla: yes, size/XXL

#394 [release-1.4] istioctl x upgrade
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest-versions.go
  cmd/mesh/manifest.go
  cmd/mesh/profile-dump.go
  cmd/mesh/root.go
  cmd/mesh/shared.go
  cmd/mesh/upgrade-hooks.go
  cmd/mesh/upgrade.go
  data/translateConfig/translateConfig-1.4.yaml
  go.mod
  go.sum
  pkg/manifest/client.go
  pkg/manifest/installer.go
  pkg/vfs/assets.gen.go
  version/version.go
  version/versions.yaml
Labels: cla: yes, size/XXL

#391 CODEOWNERS and master references for 1.4
  CODEOWNERS
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  deploy/operator.yaml
  prow/e2e_install.sh
  scripts/run_update_branch.sh
Labels: cla: yes, size/S

#392 Use relative references in the README
  ARCHITECTURE.md
  README.md
Labels: cherrypick/release-1.4, cla: yes, size/M

#397 [release-1.4] Use relative references in the README
  ARCHITECTURE.md
  README.md
Labels: cla: yes, size/M

#395 Make versions.yaml also compiled-in
  cmd/mesh/manifest-versions.go
  data/versions.yaml
  release/create_release_charts.sh
  version/version.go
  version/version.yaml
  version/version_test.go
Labels: cla: yes, size/M

#398 add shortnames for istiocontrolplane
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
Labels: cla: yes, size/XS

#396 Start to use the upgrade-hooks pkg
  cmd/mesh/upgrade-hooks.go
  cmd/mesh/upgrade.go
  pkg/hooks/upgrade_hooks.go
  pkg/hooks/upgrade_hooks_test.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#400 Add more cluster role rules for operator
  deploy/clusterrole.yaml
Labels: cla: yes, size/M

#402 Test Codeowners
  CODEOWNERS
Labels: cla: yes, size/XS

#409 [release-1.4] Make versions.yaml also compiled-in
  cmd/mesh/manifest-versions.go
  data/versions.yaml
  release/create_release_charts.sh
  version/version.go
  version/version.yaml
  version/version_test.go
Labels: cla: yes, size/M

#405 [release-1.4] Start to use the upgrade-hooks pkg
  cmd/mesh/upgrade-hooks.go
  cmd/mesh/upgrade.go
  pkg/hooks/upgrade_hooks.go
  pkg/hooks/upgrade_hooks_test.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#407 [release-1.4] Add more cluster role rules for operator
  deploy/clusterrole.yaml
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
Labels: cla: yes, size/M

#410 [release-1.4] Add script to generate migrated profile from installer
  scripts/run_migrate_profile.sh
Labels: cla: yes, size/M

#411 Controller fixes
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/component/component/component.go
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/helmreconciler/customizers.go
  pkg/helmreconciler/listeners.go
  pkg/helmreconciler/reconciler.go
  pkg/helmreconciler/rendering.go
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/L

#413 Watch only Istio-operator ns ICP CRs
  deploy/clusterrole.yaml
  deploy/operator.yaml
Labels: cla: yes, size/XS

#412 [release-1.4] Controller fixes
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/component/component/component.go
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/helmreconciler/customizers.go
  pkg/helmreconciler/listeners.go
  pkg/helmreconciler/reconciler.go
  pkg/helmreconciler/rendering.go
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cla: yes, size/L

#414 fix controller panic.
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go
Labels: cla: yes, size/S

#417 Disable output to log file by default
  .gitignore
  cmd/mesh/shared.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#418 [release-1.4] Disable output to log file by default
  .gitignore
  cmd/mesh/shared.go
Labels: cla: yes, size/S

#420 Finally figured out why code gen wasn't reliable.
  Makefile.core.mk
  pkg/apis/istio/fixup_structs/main.go
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#421 [release-1.4] Finally figured out why code gen wasn't reliable.
  Makefile.core.mk
  pkg/apis/istio/fixup_structs/main.go
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#423 Terminate yaml correctly
  deploy/clusterrole.yaml
  deploy/clusterrole_binding.yaml
  deploy/crds/istio_v1alpha2_istiocontrolplane_cr.yaml
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
  deploy/kustomization.yaml
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/service.yaml
  deploy/service_account.yaml
Labels: cherrypick/release-1.4, cla: yes, size/S

#424 Terminate yaml correctly
  deploy/clusterrole.yaml
  deploy/clusterrole_binding.yaml
  deploy/crds/istio_v1alpha2_istiocontrolplane_cr.yaml
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
  deploy/kustomization.yaml
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/service.yaml
  deploy/service_account.yaml
Labels: cla: yes, size/S

#390 replace --yes flag with --skip-confirmation flag for better usage
  cmd/mesh/manifest-apply.go
  cmd/mesh/root.go
  prow/e2e_install.sh
Labels: cla: yes, size/S

#416 Add vars for hub and tag that can be populated during build time
  cmd/mesh/profile-dump.go
  cmd/mesh/shared.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#425 [release-1.4] Add offline support for version maps of `istioctl x upgrade`
  cmd/mesh/manifest-versions.go
  cmd/mesh/manifest-versions_test.go
  cmd/mesh/testdata/manifest-versions/input/versions.yaml
  cmd/mesh/upgrade.go
  pkg/manifest/client.go
Labels: cla: yes, size/L

#429 [release-1.4] Add vars for hub and tag that can be populated during build time
  cmd/mesh/profile-dump.go
  cmd/mesh/shared.go
Labels: cla: yes, size/M

#431 gzip with `--best` the operator.tar docker file
  Makefile.core.mk
Labels: cherrypick/release-1.4, cla: yes, size/XS

#434 Add limits to the operator deployment
  deploy/operator.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#437 Use 1.5-dev tag for master
  Makefile.core.mk
Labels: cla: yes, size/XS

#438 fix bool unmarshal issue.
  pkg/apis/istio/v1alpha2/common.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/name/name.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/M

#435 [release-1.4] gzip with `--best` the operator.tar docker file
  Makefile.core.mk
Labels: cla: yes, size/XS

#426 [release-1.4] replace --yes flag with --skip-confirmation flag for better usage
  cmd/mesh/manifest-apply.go
  cmd/mesh/root.go
  prow/e2e_install.sh
Labels: cla: yes, size/S

#439 [release-1.4] fix bool unmarshal issue.
  pkg/apis/istio/v1alpha2/common.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/name/name.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cla: yes, size/M

#436 [release-1.4] Add limits to the operator deployment
  deploy/operator.yaml
Labels: cla: yes, size/XS

#440 address incorrect affinity spec
  .gitignore
  data/translateConfig/translateConfig-1.3.yaml
  data/translateConfig/translateConfig-1.4.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#447 update CRD correct links and add desp
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
Labels: cla: yes, size/S

#450 [release-1.4] address incorrect affinity spec
  .gitignore
  data/translateConfig/translateConfig-1.3.yaml
  data/translateConfig/translateConfig-1.4.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#451 [release-1.4] update CRD correct links and add desp
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
Labels: cla: yes, size/S

#433 Add upgrade short description in ARCHITECTURE.
  ARCHITECTURE.md
Labels: cla: yes, size/XS

#453 [release-1.4] Stop logs from going to console by default
  cmd/mesh/manifest-apply.go
  cmd/mesh/shared.go
Labels: cla: yes, size/S

#452 Update to common-files
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cherrypick/release-1.4, cla: yes

#448 [release-1.4]Sync installer charts for release-1.4
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#454 Sync installer charts for master
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#445 Remove disabled components when running mesh manifest apply.
  cmd/mesh/manifest-migrate.go
  cmd/mesh/upgrade.go
  pkg/component/controlplane/control_plane.go
  pkg/component/feature/feature.go
  pkg/helmreconciler/reconciler.go
  pkg/helmreconciler/rendering.go
  pkg/kubectlcmd/client.go
  pkg/kubectlcmd/client_test.go
  pkg/manifest/installer.go
Labels: cherrypick/release-1.4, cla: yes, size/L

#460 [release-1.4] fix controller panic.
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go
Labels: cla: yes, size/S

#462 [release-1.4] Remove disabled components when running mesh manifest apply.
  cmd/mesh/manifest-migrate.go
  cmd/mesh/upgrade.go
  pkg/component/controlplane/control_plane.go
  pkg/component/feature/feature.go
  pkg/helmreconciler/reconciler.go
  pkg/helmreconciler/rendering.go
  pkg/kubectlcmd/client.go
  pkg/kubectlcmd/client_test.go
  pkg/manifest/installer.go
Labels: cla: yes, size/L

#463 print meaningful error msg for patch creation.
  pkg/helmreconciler/patching.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#464 [release-1.4] print meaningful error msg for patch creation.
  pkg/helmreconciler/patching.go
Labels: cla: yes, size/XS

#458 Show reconcile status as string
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/helmreconciler/reconciler.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/S

#466 Sync to installer charts
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#457 Clean up manifest apply output
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest.go
  pkg/manifest/installer.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#469 [release-1.4] Clean up manifest apply output (#457)
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest.go
  pkg/manifest/installer.go
Labels: cla: yes, size/S

#467 [release-1.4] Show reconcile status as string (#458)
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/helmreconciler/reconciler.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cla: yes, size/XXL

#432 Update Readme
  pkg/controller/README.md
Labels: cla: yes, size/S

#468 Work around markdown conversion bug, leading to bad HTML.
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cherrypick/release-1.4, cla: yes, size/XS

#471 [release-1.4] Work around markdown conversion bug, leading to bad HTML.
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cla: yes, size/XS

#465 update installer sha.
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#473 Update readme for controller local debugging
  pkg/controller/README.md
Labels: cla: yes, size/S

#480 Properly format yaml messages
  deploy/clusterrole.yaml
  deploy/clusterrole_binding.yaml
  deploy/crds/istio_v1alpha2_istiocontrolplane_cr.yaml
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
  deploy/kustomization.yaml
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/service.yaml
  deploy/service_account.yaml
Labels: cla: yes, size/S

#483 Get the latest release-1.4 istio.io/pkg dependency.
  go.mod
  go.sum
Labels: cla: yes, size/M

#477 Refine e2e implementation
  Makefile
  Makefile.core.mk
  tests/e2e/e2e.sh
  tests/e2e/testdata/operator.yaml
Labels: cla: yes, size/L

#430 Update README
  README.md
  pkg/controller/README.md
Labels: cla: yes, size/L

#470 Add remote profile
  data/profiles/remote.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/M

#488 [release 1.4] use hub and tag from istio/pkg DockerBuildInfo
  cmd/mesh/manifest-generate_test.go
  cmd/mesh/profile-dump.go
  cmd/mesh/shared.go
  go.mod
  go.sum
Labels: cla: yes, size/M

#486 manifest diff: remove redundant empty->nil output
  pkg/compare/compare.go
  pkg/compare/compare_test.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#490 Prune citadel secrets
  pkg/controller/istiocontrolplane/listeners.go
Labels: cla: yes, size/M

#489 [release-1.4] manifest diff: remove redundant empty->nil output
  pkg/compare/compare.go
  pkg/compare/compare_test.go
Labels: cla: yes, size/M

#491 fix tpath to create leaf node when desired
  pkg/tpath/tpath.go
  pkg/tpath/tpath_test.go
Labels: cla: yes, size/S

#492 use force flag for iscp
  cmd/mesh/profile-dump.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#496 [release-1.4] Add remote profile
  data/profiles/remote.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/M

#495 [release-1.4] use force flag for iscp
  cmd/mesh/profile-dump.go
Labels: cla: yes, size/S

#493 [release-1.4] fix tpath to create leaf node when desired
  pkg/tpath/tpath.go
  pkg/tpath/tpath_test.go
Labels: cla: yes, size/S

#497 [release-1.4] Properly format yaml messages
  deploy/clusterrole.yaml
  deploy/clusterrole_binding.yaml
  deploy/crds/istio_v1alpha2_istiocontrolplane_cr.yaml
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
  deploy/kustomization.yaml
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/service.yaml
  deploy/service_account.yaml
Labels: cla: yes, size/S
