Repository istio/operator, pull requests merged in 2019-07, with the labels that each got.

#58 rename manifest object and add ut.
  pkg/component/controlplane/control_plane_test.go
  pkg/manifest/installer.go
  pkg/manifest/objects.go
  pkg/manifest/objects_test.go
  pkg/patch/patch.go
  pkg/translate/translate.go
Labels: cla: yes

#47 fix nil prune details.
  pkg/helmreconciler/listeners.go
Labels: cla: yes

#48 enhance resources waiting operation.
  pkg/controller/istiocontrolplane/listeners.go
Labels: cla: yes

#61 Create a top level README
  README.md
Labels: cla: yes

#67 add @ayj to CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#63 Fix go build command to output to iop binary
  README.md
Labels: cla: yes, ok-to-test

#66 Fix iop install
  cmd/iop/dump.go
  cmd/iop/install.go
  cmd/iop/shared.go
  data/charts/crds/templates/crds.yaml
  data/profiles/default.yaml
  pkg/component/component/component.go
  pkg/component/controlplane/control_plane_test.go
  pkg/component/controlplane/testdata/all_off.yaml
  pkg/component/controlplane/testdata/pilot_default.yaml
  pkg/component/controlplane/testdata/pilot_override_kubernetes.yaml
  pkg/component/controlplane/testdata/pilot_override_values.yaml
  pkg/kubectlcmd/client.go
  pkg/kubectlcmd/client_test.go
  pkg/manifest/installer.go
  pkg/name/name.go
  pkg/translate/translate.go
  pkg/util/path.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes

#69 fix missing crds for cert-manager.
  data/charts/crds/templates/crds.yaml
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes

#70 add feature and components for gateway.
  pkg/component/component/component.go
  pkg/component/controlplane/control_plane.go
  pkg/component/feature/feature.go
Labels: cla: yes

#77 fix error sample manifests in readme.
  README.md
Labels: cla: yes

#74 Cleanup of translate package
  pkg/component/component/component.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/translate/tree.go
Labels: cla: yes

#82 Remove nonsensical library operations for prow
  prow/lib.sh
Labels: cla: yes

#73 Cleanup and unit tests for util package
  pkg/util/common.go
  pkg/util/path.go
  pkg/util/reflect.go
  pkg/util/reflect_test.go
  pkg/validate/validate_values.go
  pkg/validate/validate_values_test.go
Labels: cla: yes

#83 Remove all circleci test cases minus test
  .circleci/config.yml
Labels: cla: yes

#84 Fix developer getting started steps
  README.md
Labels: cla: yes

#85 Emphasize that dry run is default
  README.md
Labels: cla: yes

#60 move util to common pkg.
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
  pkg/helmreconciler/customizers.go
  pkg/helmreconciler/listeners.go
  pkg/util/annotation.go
  pkg/util/label.go
Labels: cla: yes

#87 add ut for util.
  pkg/util/util_test.go
Labels: cla: yes

#65 Address missed review comments
  README.md
Labels: cla: yes

#88 iop command to compare manifests
  cmd/iop/mandiff.go
  cmd/iop/root.go
  pkg/component/controlplane/control_plane_test.go
  pkg/manifest/objects.go
Labels: cla: yes

#91 Remove vendor from makefile
  Makefile
Labels: cla: yes, size/S

#64 Initial architecture doc
  ARCHITECTURE.md
  images/operator_render_flow.svg
Labels: cla: yes

#89 fix broken probe in generated manifests.
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
  pkg/apis/istio/v1alpha2/fixup_go_structs.patch
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/values_types.go
  pkg/util/util_test.go
  pkg/validate/validate_test.go
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XXL

#100 Work around lint problem
  Makefile
Labels: cla: yes, size/XS

#101 Adding iops.log to .gitignore.
  .gitignore
Labels: cla: yes, size/XS

#96 Link ARCHITECTURE.md to README.md
  README.md
Labels: cla: yes, size/XS

#102 Remove prow directory
  prow/build.sh
  prow/istio-lint.sh
  prow/lib.sh
  prow/lint.sh
  prow/test.sh
Labels: cla: yes, size/L

#98 Sync charts with istio/installer
  data/charts/crds/templates/crds.yaml
  data/charts/gateways/istio-egress/templates/deployment.yaml
  data/charts/gateways/istio-ingress/templates/addongateway.yaml
  data/charts/gateways/istio-ingress/templates/deployment.yaml
  data/charts/gateways/istio-ingress/values.yaml
  data/charts/istio-control/istio-autoinject/files/injection-template.yaml
  data/charts/istio-control/istio-autoinject/templates/clusterrole.yaml
  data/charts/istio-control/istio-autoinject/templates/deployment.yaml
  data/charts/istio-control/istio-config/templates/clusterrole.yaml
  data/charts/istio-control/istio-config/templates/deployment.yaml
  data/charts/istio-control/istio-config/templates/validatingwebhookconfiguration.yaml.tpl
  data/charts/istio-control/istio-discovery/templates/configmap.yaml
  data/charts/istio-control/istio-discovery/templates/deployment.yaml
  data/charts/istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
  data/charts/istio-control/istio-discovery/values.yaml
  data/charts/istio-policy/templates/deployment.yaml
  data/charts/istio-telemetry/grafana/templates/deployment.yaml
  data/charts/istio-telemetry/grafana/templates/ingress.yaml
  data/charts/istio-telemetry/kiali/templates/deployment.yaml
  data/charts/istio-telemetry/mixer-telemetry/templates/deployment.yaml
  data/charts/istio-telemetry/prometheus/templates/deployment.yaml
  data/charts/istio-telemetry/tracing/templates/deployment-jaeger.yaml
  data/charts/istio-telemetry/tracing/templates/deployment-opencensus.yaml
  data/charts/istio-telemetry/tracing/templates/deployment-zipkin.yaml
  data/charts/istio-telemetry/tracing/templates/service.yaml
  data/charts/istio-telemetry/tracing/values.yaml
  data/charts/security/certmanager/templates/NOTES.txt
  data/charts/security/certmanager/templates/deployment.yaml
  data/charts/security/citadel/templates/NOTES.txt
  data/charts/security/citadel/templates/clusterrole.yaml
  data/charts/security/citadel/templates/deployment.yaml
  data/charts/security/citadel/templates/poddisruptionbudget.yaml
  data/charts/security/citadel/values.yaml
  data/charts/security/nodeagent/templates/daemonset.yaml
  go.mod
  go.sum
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XXL

#94 Remove circleci
  .circleci/accounts/istio-github.enc
  .circleci/config.yml
  README.md
  scripts/codecov.sh
  scripts/codecov_diff.sh
Labels: cla: yes, size/L

#79 Create values proto and go struct
  Makefile
  go.sum
  pkg/apis/istio/v1alpha2/values/fix_values_structs.patch
  pkg/apis/istio/v1alpha2/values/values_types.pb.go
  pkg/apis/istio/v1alpha2/values/values_types.proto
Labels: cla: yes, size/XXL

#81 Cleanup validate
  cmd/iop/mandiff.go
  go.mod
  pkg/component/controlplane/control_plane_test.go
  pkg/manifest/installer.go
  pkg/object/objects.go
  pkg/object/objects_test.go
  pkg/patch/patch.go
  pkg/tpath/tpath.go
  pkg/tpath/tpath_test.go
  pkg/translate/translate.go
  pkg/translate/tree.go
  pkg/translate/tree_test.go
  pkg/util/common.go
  pkg/util/reflect.go
  pkg/util/reflect_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  pkg/util/yaml.go
  pkg/validate/common.go
Labels: cla: yes, size/XXL

#103 Sync charts
  data/charts/crds/templates/crds.yaml
  data/charts/crds/templates/namespaces.yaml
Labels: cla: yes, size/L

#92 Add flags to dump-config command
  cmd/iop/dump.go
  cmd/iop/root.go
  cmd/iop/shared.go
  pkg/component/component/component.go
  pkg/translate/translate.go
Labels: cla: yes, size/L

#35 Initial implementation of fetcher of remote charts url
  go.mod
  go.sum
  pkg/helm/testdata/istio-installer.tar.gz
  pkg/helm/testdata/istio-installer.tar.gz.sha256
  pkg/helm/urlfetcher.go
  pkg/helm/urlfetcher_test.go
  pkg/helm/urlwatcher.go
Labels: cla: yes, size/XL

#99 Add error logs for various scenarios. Update existing log messages and…
  cmd/iop/dump.go
  cmd/iop/install.go
  cmd/iop/manifest.go
  cmd/iop/root.go
  cmd/iop/shared.go
  cmd/manager/server.go
  cmd/vfsgen/vfsgen.go
  pkg/helm/fs_renderer.go
  pkg/helm/helm.go
  pkg/helm/vfs_renderer.go
  pkg/kubectlcmd/client.go
  pkg/manifest/installer.go
  pkg/object/objects.go
  pkg/translate/translate.go
  pkg/validate/common.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: cla: yes, ok-to-test, size/L

#93 Fix file path error of fix_values_structs patch.
  Makefile
Labels: cla: yes, size/XS

#108 Remove mergify
  .mergify.yml
  README.md
Labels: cla: yes, size/S

#107 Makefile: specify dependencies for vfsgen. Add iop target.
  Makefile
  README.md
Labels: cla: yes, ok-to-test, size/S

#106 fix port unmarshal issue and add ut.
  pkg/apis/istio/v1alpha2/values_types.go
  pkg/util/yaml_test.go
  pkg/validate/validate_test.go
Labels: cla: yes, size/M

#95 Add prow test for manifest compare.
  .gitignore
  Makefile
  bin/init_helm.sh
  data/charts/crds/templates/crds.yaml
  pkg/vfsgen/vfsgen_data.go
  scripts/run_mandiff.sh
  tests/profiles/helm/values-istio-default.yaml
  tests/profiles/helm/values-istio-demo-auth.yaml
  tests/profiles/helm/values-istio-demo.yaml
  tests/profiles/helm/values-istio-minimal.yaml
  tests/profiles/helm/values-istio-sds.yaml
  tests/profiles/iop/default-profile.yaml
  tests/profiles/iop/demo-auth-profile.yaml
  tests/profiles/iop/demo-profile.yaml
  tests/profiles/iop/minimal-profile.yaml
  tests/profiles/iop/sds-profile.yaml
Labels: cla: yes, size/XL

#111 workaround gopath for mandiff.
  Makefile
Labels: cla: yes, size/XS

#109 Add a test target
  Makefile
Labels: cla: yes, size/S

#112 Improve error logs
  cmd/iop/dump.go
  cmd/iop/install.go
  cmd/iop/shared.go
Labels: cla: yes, size/M

#117 Add missing fields to proto
  pkg/apis/istio/v1alpha2/values/values_types.proto
Labels: cla: yes, size/XS

#121 Remove v1alpha2 dependency from util
  pkg/object/objects_test.go
  pkg/util/yaml_test.go
Labels: cla: yes, size/L

#110 support log level and scope.
  cmd/iop/dump.go
  cmd/iop/install.go
  cmd/iop/mandiff.go
  cmd/iop/manifest.go
  cmd/iop/root.go
  cmd/iop/shared.go
  pkg/name/name.go
  pkg/patch/patch.go
  pkg/tpath/tpath.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/util/common.go
  pkg/util/reflect.go
  pkg/util/util.go
  pkg/util/yaml.go
  pkg/validate/common.go
  pkg/validate/validate.go
  pkg/validate/validate_values.go
Labels: cla: yes, size/L

#123 Fix ARCHITECTURE.md
  ARCHITECTURE.md
Labels: cla: yes, size/S

#105 Update mesh command layout per CLI review
  .gitignore
  ARCHITECTURE.md
  Makefile
  README.md
  cmd/iop/dump.go
  cmd/iop/manifest.go
  cmd/iop/shared.go
  cmd/mesh.go
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-diff.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest-migrate.go
  cmd/mesh/manifest.go
  cmd/mesh/profile-diff.go
  cmd/mesh/profile-dump.go
  cmd/mesh/profile-list.go
  cmd/mesh/profile.go
  cmd/mesh/root.go
  cmd/mesh/shared.go
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
  pkg/component/component/component.go
  pkg/helm/helm.go
  pkg/manifest/installer.go
  pkg/util/yaml.go
  pkg/validate/validate.go
  pkg/vfsgen/vfsgen_data.go
  samples/customize_pilot.yaml
  scripts/run_mandiff.sh
  tests/profiles/mesh/default-profile.yaml
  tests/profiles/mesh/demo-auth-profile.yaml
  tests/profiles/mesh/demo-profile.yaml
  tests/profiles/mesh/minimal-profile.yaml
  tests/profiles/mesh/sds-profile.yaml
Labels: cla: yes, size/XXL

#104 Cleanup and changes based on CLI review
  ARCHITECTURE.md
  cmd/mesh/profile-dump.go
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
  pkg/apis/istio/v1alpha2/fixup_go_structs.patch
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/component/component/component.go
  pkg/component/controlplane/control_plane_test.go
  pkg/helm/helm.go
  pkg/name/name.go
  pkg/object/objects_test.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/util/common.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: cla: yes, size/XL

#127 Add @richardwxn to code owner
  CODEOWNERS
Labels: cla: yes, size/XS

#126 Version plumbing for operator
  cmd/mesh/manifest-apply.go
  go.mod
  pkg/component/controlplane/control_plane_test.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/version/version.go
  pkg/version/version_test.go
  version/version.go
  version/version_test.go
  version/versions.yaml
Labels: cla: yes, size/L

#130 fix unknown field for unmarshaling.
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
Labels: cla: yes, size/S

#135 Fix the invalid metadata.labels
  pkg/version/version.go
Labels: cla: yes, size/XS

#134 fix incorrect hpa scale target ref.
  data/profiles/default.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
Labels: cla: yes, size/S

#133 Remove repeated from gateway fields, related fixes
  cmd/mesh/manifest-generate.go
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/component/component/component.go
  pkg/helm/vfs_renderer.go
  pkg/name/name.go
  pkg/vfsgen/vfsgen_data.go
  tests/profiles/mesh/default-profile.yaml
  tests/profiles/mesh/demo-auth-profile.yaml
  tests/profiles/mesh/demo-profile.yaml
  tests/profiles/mesh/minimal-profile.yaml
  tests/profiles/mesh/sds-profile.yaml
Labels: cla: yes, size/XL

#124 update function writeStringSafe so as to print diff string
  pkg/object/objects.go
Labels: cla: yes, size/S

#137 update gateway fields to use CommonComponentSpec
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
Labels: cla: yes, size/XXL

#138 Fixes to charts to make manifest apply work
  cmd/mesh/manifest-apply.go
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
  go.mod
  go.sum
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/kubectlcmd/client.go
  pkg/manifest/installer.go
  pkg/object/objects.go
  pkg/translate/translate.go
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XXL

#139 fix namespace not found issue.
  README.md
  data/charts/crds/templates/namespaces.yaml
  data/charts/global.yaml
  pkg/translate/translate.go
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XL

#136 Support wait for manifest apply.
  cmd/mesh/manifest-apply.go
  pkg/manifest/installer.go
Labels: cla: yes, size/L

#129 Add validation for IP ranges in operator's validate.go
  pkg/name/name.go
  pkg/util/reflect.go
  pkg/validate/common.go
  pkg/validate/validate.go
  pkg/validate/validate_values.go
  pkg/validate/validate_values_test.go
Labels: cla: yes, size/M
