Repository istio/operator, pull requests merged in 2019-09, with the labels that each got.

#243 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/XS

#244 Fix env value type
  pkg/translate/translate_value.go
Labels: cla: yes, size/XS

#227 Add values validation
  cmd/mesh/profile-diff.go
  cmd/mesh/profile-dump.go
  pkg/helm/helm.go
  pkg/manifest/installer.go
  pkg/validate/common.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
  pkg/validate/validate_values.go
  pkg/validate/validate_values_test.go
Labels: cla: yes, size/L

#242 Add basic e2e tests
  prow/e2e_install.sh
  prow/k8s/mtls_permissive.yaml
  prow/k8s/mtls_strict.yaml
  prow/k8s/sidecar-local.yaml
Labels: cla: yes, size/L

#245 simplify logic for reverse translation of slices
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  pkg/translate/translate_value.go
Labels: cla: yes, size/L

#248 Revert go-bindata due to release build issues (#241)
  Makefile.core.mk
  cmd/vfsgen/vfsgen.go
  go.mod
  go.sum
  pkg/vfs/assets.gen.go
  pkg/vfs/vfs.go
Labels: cla: yes, size/XXL

#249 Stabilizing manifest generation to create text diffable output
  cmd/mesh/manifest-generate_test.go
  pkg/helm/helm.go
Labels: cla: yes, ok-to-test, size/M

#255 Revert "Revert go-bindata due to release build issues (#241) (#248)"
  Makefile.core.mk
  cmd/vfsgen/vfsgen.go
  go.mod
  go.sum
  pkg/vfs/assets.gen.go
  pkg/vfs/vfs.go
Labels: cla: yes, size/XXL

#250 Usage messages, grammar, and manifest apply --yes opt
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-diff.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest-generate_test.go
  cmd/mesh/manifest-migrate.go
  cmd/mesh/manifest-versions.go
  cmd/mesh/manifest.go
  cmd/mesh/profile-diff.go
  cmd/mesh/profile-dump.go
  cmd/mesh/profile-list.go
  cmd/mesh/profile.go
  cmd/mesh/root.go
  cmd/mesh/shared.go
  pkg/kubectlcmd/client.go
Labels: cla: yes, size/L

#258 Add protocolDetectionTimeout
  data/profiles/default.yaml
Labels: cla: yes, size/XS

#257 Sync installer charts SHA
  Makefile.core.mk
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#259 Fix proto patching hack
  Makefile.core.mk
  pkg/apis/istio/v1alpha2/fixup_go_structs.patch
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cla: yes, size/XL

#260 Fix html generation
  Makefile.core.mk
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/apis/istio/v1alpha2/values/values.pb.html
Labels: cla: yes, size/L

#263 [release-1.3] Add protocolDetectionTimeout
  data/profiles/default.yaml
Labels: cla: yes, size/XS

#264 [release-1.3] Fix proto patching hack
  Makefile.core.mk
  pkg/apis/istio/v1alpha2/fixup_go_structs.patch
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cla: yes, size/XL

#265 [release-1.3] Fix html generation
  Makefile.core.mk
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/apis/istio/v1alpha2/values/values.pb.html
Labels: cla: yes, size/L

#246 Add kind setup back
  prow/e2e_install.sh
Labels: cla: yes, size/M

#256 manifest diff: add text diff when --verbose flag is set.
  cmd/mesh/manifest-diff.go
  cmd/mesh/manifest-generate_test.go
  pkg/object/objects.go
  pkg/object/objects_test.go
Labels: cla: yes, size/M

#267 Restore correct format for HTML docs
  Makefile.core.mk
  pkg/apis/istio/v1alpha2/istio.operator.v1alpha2.pb.html
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cla: yes, size/XXL

#268 Fix doc generation.
  Makefile.core.mk
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/apis/istio/v1alpha2/values/values.pb.html
  pkg/apis/istio/v1alpha2/values/values_types.pb.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#274 Usage messages, grammar, and manifest apply --yes opt (#250)
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-diff.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest-generate_test.go
  cmd/mesh/manifest-migrate.go
  cmd/mesh/manifest-versions.go
  cmd/mesh/manifest.go
  cmd/mesh/profile-diff.go
  cmd/mesh/profile-dump.go
  cmd/mesh/profile-list.go
  cmd/mesh/profile.go
  cmd/mesh/root.go
  cmd/mesh/shared.go
  pkg/kubectlcmd/client.go
Labels: cla: yes, size/L

#271 fix nodeselector path in k8s overlay.
  README.md
  cmd/mesh/testdata/manifest-generate/input/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  pkg/translate/translate.go
  samples/pilot-k8s.yaml
Labels: cla: yes, size/S

#275 [release-1.3] fix nodeselector path in k8s overlay.
  README.md
  cmd/mesh/testdata/manifest-generate/input/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  pkg/translate/translate.go
  samples/pilot-k8s.yaml
Labels: cla: yes, size/S

#269 add toleration in k8s overlay settings
  README.md
  cmd/mesh/testdata/manifest-generate/input/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/translate/translate.go
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
  pkg/util/reflect.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
  samples/pilot-k8s.yaml
Labels: cla: yes, size/XL

#276 Enable more linters in this repo.
  Makefile.core.mk
  build/Dockerfile
  prow/e2e_install.sh
  release/create_release_charts.sh
  release/update_version.sh
  scripts/run_mandiff.sh
  scripts/run_update_charts.sh
Labels: cla: yes, size/M

#251 Fix ordering of manifest diff output
  pkg/object/objects.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#278 Doc updates.
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/apis/istio/v1alpha2/values/values.pb.html
  pkg/apis/istio/v1alpha2/values/values_types.pb.go
  pkg/apis/istio/v1alpha2/values/values_types.proto
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.3, cla: yes, size/L

#279 Update installer charts SHA
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#280 remove notes file from render output.
  pkg/helm/helm.go
Labels: cla: yes, size/XS

#247 strategic merge overlay from operator api to values.
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  pkg/name/name.go
  pkg/translate/translate.go
Labels: cla: yes, size/L

#262 Sync to installer charts
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#285 Update common files
  Makefile
  cmd/mesh/manifest-migrate.go
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/lint_go.sh
  pkg/apis/istio/v1alpha2/values_types.go
  pkg/helmreconciler/listeners.go
  pkg/manifest/installer.go
  pkg/translate/translate_value.go
Labels: cla: yes, size/M

#287 [release-1.3] remove notes file from render output.
  pkg/helm/helm.go
Labels: cla: yes, size/XS

#288 Scrub TODOs: convert to issues, fix or delete
  cmd/mesh/manifest-generate_test.go
  pkg/manifest/installer.go
  pkg/name/name.go
  pkg/object/objects.go
  pkg/patch/patch.go
  pkg/tpath/tpath.go
  pkg/util/reflect_test.go
  pkg/values/values_test.go
  release/create_release_charts.sh
Labels: cla: yes, size/M

#289 [release-1.3] Scrub TODOs: convert to issues, fix or delete
  cmd/mesh/manifest-generate_test.go
  pkg/manifest/installer.go
  pkg/name/name.go
  pkg/object/objects.go
  pkg/patch/patch.go
  pkg/tpath/tpath.go
  pkg/util/reflect_test.go
  pkg/values/values_test.go
  release/create_release_charts.sh
Labels: cla: yes, size/M

#291 Update to kubernetes 1.15 libraries
  cmd/manager/server.go
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  go.mod
  go.sum
  pkg/helmreconciler/pruning.go
  prow/e2e_install.sh
Labels: cla: yes, size/XL

#292 Fix e2e test
  prow/e2e_install.sh
Labels: cla: yes, size/S

#293 add script to update version for release branch.
  scripts/run_update_branch.sh
Labels: cla: yes, size/M

#294 update operator version in script.
  scripts/run_update_branch.sh
Labels: cla: yes, size/XS

#290 Add obj diff inside the yaml text in ConfigMap data
  pkg/compare/compare.go
  pkg/compare/compare_test.go
Labels: cla: yes, size/L

#286 support telemetry addons
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  data/profiles/minimal.yaml
  pkg/component/component/component.go
  pkg/component/controlplane/control_plane.go
  pkg/manifest/installer.go
  pkg/name/name.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/translate/translate_value.go
  scripts/run_mandiff.sh
Labels: cla: yes, size/XXL

#297 [release-1.3] Fix e2e test
  prow/e2e_install.sh
Labels: cla: yes, size/S

#296 [release-1.3] Add obj diff inside the yaml text in ConfigMap data
  pkg/compare/compare.go
  pkg/compare/compare_test.go
Labels: cla: yes, size/L

#298 Update common files and protos.
  Makefile
  Makefile.core.mk
  common-protos/.commonfiles.sha
  common-protos/google/protobuf/compiler/ruby/ruby_generated_code.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_code_proto2.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_legacy.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_pkg_implicit.proto
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/L

#295 Add test for setting output directory for manifest generate
  cmd/mesh/manifest-generate_test.go
  cmd/mesh/testdata/manifest-generate/input/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/input/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
Labels: cla: yes, ok-to-test, size/XXL

#299 [release-1.3] support telemetry addons (#286)
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  data/profiles/minimal.yaml
  pkg/component/component/component.go
  pkg/component/controlplane/control_plane.go
  pkg/manifest/installer.go
  pkg/name/name.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/translate/translate_value.go
  scripts/run_mandiff.sh
Labels: cla: yes, size/XXL

#300 Move translations info table into translateConfig-1.3.yaml
  data/translateConfig/translateConfig-1.3.yaml
  pkg/translate/translate.go
  pkg/translate/translate_value.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XL

#272 Update values schema
  Makefile.core.mk
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  data/profiles/minimal.yaml
  go.mod
  go.sum
  pkg/apis/istio/fixup_structs/main.go
  pkg/apis/istio/v1alpha1/common.go
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/apis/istio/v1alpha2/common.go
  pkg/apis/istio/v1alpha2/validation/validation.go
  pkg/apis/istio/v1alpha2/validation/validation_test.go
  pkg/apis/istio/v1alpha2/values_types.go
  pkg/translate/translate_value_test.go
  pkg/util/yaml.go
  pkg/validate/validate_test.go
  pkg/validate/validate_values.go
  pkg/validate/validate_values_test.go
  pkg/values/testdata/values/cert-manager.yaml
  pkg/values/testdata/values/citadel.yaml
  pkg/values/testdata/values/cni.yaml
  pkg/values/testdata/values/discovery.yaml
  pkg/values/testdata/values/egress-gateway.yaml
  pkg/values/testdata/values/galley.yaml
  pkg/values/testdata/values/global.yaml
  pkg/values/testdata/values/grafana.yaml
  pkg/values/testdata/values/ingress-gateway.yaml
  pkg/values/testdata/values/nodeagent.yaml
  pkg/values/testdata/values/policy.yaml
  pkg/values/testdata/values/prometheus-operator.yaml
  pkg/values/testdata/values/sidecar-injector.yaml
  pkg/values/values_test.go
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
  python/istio_api/pkg/apis/istio/v1alpha2/values/values_types_pb2.py
Labels: cla: yes, size/XXL

#283 add cni feature
  data/profiles/default.yaml
  data/translateConfig/translateConfig-1.3.yaml
  go.mod
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/component/feature/feature.go
  pkg/manifest/installer.go
  pkg/name/name.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cla: yes, size/M

#308 Update common files.
  Makefile
  Makefile.core.mk
  common-protos/.commonfiles.sha
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/gobuild.sh
  go.mod
Labels: cla: yes, size/L

#304 manifest diff: add resource rename flag
  cmd/mesh/manifest-diff.go
  cmd/mesh/manifest-generate_test.go
  pkg/object/objects.go
  pkg/object/objects_test.go
Labels: cla: yes, size/L
