Repository istio/operator, pull requests merged in 2019-11, with the labels that each got.

#503 fix `make update-golden` when run from a Mac
  Makefile.core.mk
Labels: cla: yes, size/XS

#500 Turn off DNS certificate provisioning
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/XXL

#494 [release-1.4] Prune citadel secrets
  pkg/controller/istiocontrolplane/listeners.go
Labels: cla: yes, size/M

#505 Cherrypick "Turn off DNS certificate provisioning" (#500)
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#476 Exclude the overridden values when comparing the old with the new ones.
  cmd/mesh/profile-dump.go
  cmd/mesh/upgrade.go
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/object/objects.go
  pkg/tpath/tpath.go
Labels: cla: yes, size/L

#499 Fix cryptic messages.
  cmd/mesh/upgrade.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#509 Stabilize k8s overlay output order
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  pkg/object/objects.go
  pkg/patch/patch.go
Labels: cla: yes, size/XXL

#508 [release-1.4] Fix cryptic messages.
  cmd/mesh/upgrade.go
Labels: cla: yes, size/S

#507 [release-1.4] Exclude the overridden values when comparing the old with the new one…
  cmd/mesh/profile-dump.go
  cmd/mesh/upgrade.go
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/object/objects.go
  pkg/tpath/tpath.go
Labels: cla: yes, size/L

#506 Add force flag for set override and update CNI schema
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest.go
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/upgrade.go
  pkg/apis/istio/fixup_structs/main.go
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/apis/istio/v1alpha2/validation/validation_test.go
  pkg/validate/validate_values_test.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/L

#510 Fix order for overlay as well
  pkg/patch/patch.go
Labels: cla: yes, size/S

#511 [release-1.4] fix for cni, force flag update and manifest-generate output order
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest.go
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/upgrade.go
  pkg/apis/istio/fixup_structs/main.go
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/apis/istio/v1alpha2/validation/validation_test.go
  pkg/object/objects.go
  pkg/patch/patch.go
  pkg/validate/validate_values_test.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/XXL

#512 Update common files
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#513 Update installer SHA
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#515 Sync installer charts
  Makefile.core.mk
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#474 Fix reverse translate issue
  cmd/mesh/manifest-migrate.go
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  pkg/translate/translate_value.go
Labels: cla: yes, size/S

#518 Don't watch jobs, which are not created
  pkg/controller/istiocontrolplane/pruningdetails.go
Labels: cla: yes, size/XS

#519 [release-1.4] Don't watch jobs, which are not created
  pkg/controller/istiocontrolplane/pruningdetails.go
Labels: cla: yes, size/XS

#520 Sync installer charts
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#517 Try add a hint to use force flag
  pkg/validate/validate.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#521 [release-1.4] Try add a hint to use force flag
  pkg/validate/validate.go
Labels: cla: yes, size/XS

#525 Fix the concurrent map writes error on CompositeOutput.
  pkg/manifest/installer.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#526 [release-1.4] Fix the concurrent map writes error on CompositeOutput.
  pkg/manifest/installer.go
Labels: cla: yes, size/XS

#522 Fix enablement path for CNI
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#478 Add multicluster remote gateway install YAML for mesh command
  data/examples/multicluster/values-istio-multicluster-gateways.yaml
  data/examples/multicluster/values-istio-multicluster-primary.yaml
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#527 [release-1.4] Add multicluster remote gateway install YAML for mesh command
  data/examples/multicluster/values-istio-multicluster-gateways.yaml
  data/examples/multicluster/values-istio-multicluster-primary.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/M

#523 Add CoreDNS feature and component
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  data/translateConfig/translateConfig-1.4.yaml
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/component/component/component.go
  pkg/component/feature/feature.go
  pkg/name/name.go
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/L

#529 [release 1.4] Fix enablement path for CNI (#522)
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/M

#530 [release-1.4] Add CoreDNS feature and component (#523)
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  data/translateConfig/translateConfig-1.4.yaml
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/component/component/component.go
  pkg/component/feature/feature.go
  pkg/name/name.go
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cla: yes, size/L

#531 Fix profile hub and tag for 1.4
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
Labels: cla: yes, size/S

#533 Sync installer charts
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#535 Send errors to stderr
  cmd/mesh/shared.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#536 [release-1.4] Send errors to stderr
  cmd/mesh/shared.go
Labels: cla: yes, size/M

#528 Update installer SHA and remove security.trustDomain
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/L

#532 Fix type panic caused by some compare paths are deeper than overrides, but not supported by GetFromTreePath()
  pkg/name/name.go
  pkg/name/name_test.go
  pkg/tpath/tpath.go
Labels: cherrypick/release-1.4, cla: yes, size/L

#524 Add a few more values as typed config
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/S

#537 Remove demo-auth profile
  cmd/mesh/profile-dump_test.go
  cmd/mesh/testdata/profile-dump/input/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  data/profiles/demo-auth.yaml
  pkg/validate/validate_values_test.go
  pkg/vfs/assets.gen.go
  scripts/run_mandiff.sh
  tests/profiles/helm/values-istio-demo-auth.yaml
  tests/profiles/helm/values-istio-demo.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XL

#538 [release-1.4] Fix type panic caused by some compare paths are deeper than overrides, but not supported by GetFromTreePath()
  pkg/name/name.go
  pkg/name/name_test.go
  pkg/tpath/tpath.go
Labels: cla: yes, size/L

#539 Add a few more values as typed config (#524)
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/S

#540 Remove demo-auth profile (#537)
  cmd/mesh/profile-dump_test.go
  cmd/mesh/testdata/profile-dump/input/demo-auth_certmanager_on.yaml
  cmd/mesh/testdata/profile-dump/output/demo-auth_certmanager_on.yaml
  data/profiles/demo-auth.yaml
  pkg/validate/validate_values_test.go
  pkg/vfs/assets.gen.go
  scripts/run_mandiff.sh
  tests/profiles/helm/values-istio-demo-auth.yaml
  tests/profiles/helm/values-istio-demo.yaml
Labels: cla: yes, size/XL

#541 Update binary output path
  README.md
Labels: cla: yes, size/XS

#542 Sync installer
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#543 Sync release-1.4 charts
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XL

#546 Sync release-1.4 charts
  go.sum
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#547 Add trust domain aliases to global config
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/XS

#545 Copy operator examples into release tar
  release/create_release_charts.sh
Labels: cherrypick/release-1.4, cla: yes, size/XS

#548 [release-1.4] Copy operator examples into release tar
  release/create_release_charts.sh
Labels: cla: yes, size/XS

#552 Do not create kiali secret on default profile
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#550 Cherrypick for #547
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/XS

#553 Do not create kiali secret on default profile
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#551 Enable ingress in remote profile
  data/profiles/remote.yaml
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#554 [release-1.4] Enable ingress in remote profile
  data/profiles/remote.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#555 Fix error messages into output
  cmd/mesh/profile-dump.go
  pkg/kubectlcmd/client.go
  pkg/validate/validate.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#556 [release-1.4] Fix error messages into output
  cmd/mesh/profile-dump.go
  pkg/kubectlcmd/client.go
  pkg/validate/validate.go
Labels: cla: yes, size/S

#558 [release-1.4] Sync to installer
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  data/translateConfig/translateConfig-1.4.yaml
  installer.sha
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go
  pkg/name/name.go
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
  release/create_release_charts.sh
  scripts/run_mandiff.sh
  scripts/run_update_charts.sh
Labels: cla: yes, size/XXL

#557 Sync to installer
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  data/translateConfig/translateConfig-1.4.yaml
  installer.sha
  pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go
  pkg/name/name.go
  pkg/vfs/assets.gen.go
  release/create_release_charts.sh
  scripts/run_mandiff.sh
  scripts/run_update_charts.sh
Labels: cla: yes, size/XXL

#559 Fix aud for sds
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  data/profiles/sds.yaml
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#562 Backport sds aud
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  data/profiles/sds.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#549 Update reverse translation for coredns
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#561 Fix podDNSSearchNamespaces validation issue
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/validate/validate_values_test.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/S

#563 Sync installer charts
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/M

#566 Add ldflags override for hub/tag in controller
  cmd/mesh/profile-dump.go
  pkg/helm/helm.go
  pkg/helmreconciler/rendering.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#564 Drop log levels from info to debug
  pkg/component/component/component.go
  pkg/helm/vfs_renderer.go
  pkg/translate/translate.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#570 [release-1.4] Drop log levels from info to debug
  pkg/component/component/component.go
  pkg/helm/vfs_renderer.go
  pkg/translate/translate.go
Labels: cla: yes, size/S

#568 [release-1.4] Add ldflags override for hub/tag in controller
  cmd/mesh/profile-dump.go
  pkg/helm/helm.go
  pkg/helmreconciler/rendering.go
Labels: cla: yes, size/M

#567 [release-1.4] Fix podDNSSearchNamespaces validation issue (#561)
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/validate/validate_values_test.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/S

#571 Remove unnecessary metadata validation part
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
Labels: cherrypick/release-1.4, cla: yes

#573 [release-1.4] Remove unnecessary metadata validation part
  deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
Labels: cla: yes, size/XS

#572 [release-1.4] Update reverse translation for (#549)
  cmd/mesh/manifest-migrate.go
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
Labels: cla: yes, size/M

#565 Add fields to values schema
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cherrypick/release-1.4, cla: yes, size/M

#574 Updates to dependencies
  Makefile
  Makefile.core.mk
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  common/.commonfiles.sha
  common/Makefile.common.mk
  installer.sha
  licenses/github.com/BurntSushi/xgb/COPYING
  licenses/github.com/gogo/googleapis/LICENSE
  licenses/github.com/grpc-ecosystem/grpc-gateway/LICENSE
  licenses/github.com/hpcloud/tail/Licence
  licenses/github.com/ugorji/go/LICENSE
  licenses/go.etcd.io/bbolt/LICENSE
  licenses/gonum.org/v1/gonum/LICENSE.txt
  licenses/modernc.org/cc/COPYING
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#575 [release-1.4] Sync installer charts
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XL

#576 [release-1.4] Add fields to values schema (#565)
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/M

#581 Update common files
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/S

#580 fix icp fields after reconciling.
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#582 [release-1.4] fix icp fields after reconciling.
  pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
Labels: cla: yes, size/S

#579 Remove unnecessary proxy translation path
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  data/translateConfig/translateConfig-1.4.yaml
  pkg/translate/translate_value_test.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#584 Turn on control plane security for sds
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/sds.yaml
  pkg/vfs/assets.gen.go
  tests/profiles/helm/values-istio-sds.yaml
Labels: cherrypick/release-1.4, cla: yes, size/XS

#585 [release-1.4] Turn on control plane security for sds
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/sds.yaml
  pkg/vfs/assets.gen.go
  tests/profiles/helm/values-istio-sds.yaml
Labels: cla: yes, size/XS

#586 Installation option doc cleanup
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cherrypick/release-1.4, cla: yes, size/XS

#587 [release-1.4] Installation option doc cleanup
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
Labels: cla: yes, size/XS

#577 Create namespace before namespaced resources in Base component, fixin…
  pkg/manifest/installer.go
Labels: cherrypick/release-1.4, cla: yes, size/L

#589 [release-1.4] Create namespace before namespaced resources in Base component, fixin…
  pkg/manifest/installer.go
Labels: cla: yes, size/L

#588 Move gateway and coredns enablement in sample config
  data/examples/multicluster/values-istio-multicluster-gateways.yaml
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#593 [release-1.4] Move gateway and coredns enablement in sample config
  data/examples/multicluster/values-istio-multicluster-gateways.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#595 Move meshNetworks network1,2 under networks:
  data/examples/multicluster/values-istio-multicluster-primary.yaml
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#583 Update error message
  cmd/mesh/manifest.go
Labels: cla: yes, size/XS

#596 [release-1.4] Move meshNetworks network1,2 under networks:
  data/examples/multicluster/values-istio-multicluster-primary.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#597 Sync installer
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#598 Sync installer in master
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#592 Make apply errors more visible
  cmd/mesh/manifest.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#599 [release-1.4] Make apply errors more visible
  cmd/mesh/manifest.go
Labels: cla: yes, size/XS

#601 Move gateway enablement in sample config
  data/examples/multicluster/values-istio-multicluster-gateways.yaml
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes

#603 [release-1.4] Move gateway enablement in sample config
  data/examples/multicluster/values-istio-multicluster-gateways.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#600 Update installer SHA
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/L

#602 Move telemetry out of pilot
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  installer.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/XXL

#604 sync installer.
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#606 [release-1.4] Update error message
  cmd/mesh/manifest.go
Labels: cla: yes, size/XS

#607 fix fetch of go-bindata in README.md
  README.md
Labels: cla: yes, size/XS

#605 Add vm for multi network support sample
  data/examples/vm/values-istio-meshexpansion-gateways.yaml
  data/examples/vm/values-istio-meshexpansion.yaml
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#609 [release-1.4] Add vm for multi network support sample
  data/examples/vm/values-istio-meshexpansion-gateways.yaml
  data/examples/vm/values-istio-meshexpansion.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/M

#608 Use gobuild.sh to build operator
  Makefile.core.mk
Labels: cherrypick/release-1.4, cla: yes, size/XS

#610 Use gobuild.sh to build operator (#608)
  Makefile.core.mk
Labels: cla: yes, size/XS

#591 update manifest migrate commands
  cmd/mesh/manifest-migrate.go
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
  pkg/util/yaml.go
  pkg/validate/validate_values.go
  scripts/run_migrate_profile.sh
Labels: cherrypick/release-1.4, cla: yes, size/XXL

#612 Update installer deps
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#613 [release-1.4] update manifest migrate commands (#591)
  cmd/mesh/manifest-migrate.go
  cmd/mesh/testdata/manifest-migrate/output/values.yaml
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
  pkg/util/yaml.go
  pkg/validate/validate_values.go
  scripts/run_migrate_profile.sh
Labels: cla: yes, size/XXL

#614 update telemetryv2 name
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/XS

#615 fix values overlay
  pkg/component/component/component.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#617 [release-1.4] fix values overlay
  pkg/component/component/component.go
Labels: cla: yes, size/XS

#616 update env value to take different types
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest.go
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/S

#619 fix operator pruning list.
  pkg/controller/istiocontrolplane/pruningdetails.go
Labels: cla: yes, size/XS

#620 update minimal profile
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  data/profiles/minimal.yaml
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/M

#621 [release-1.4]update minimal profile (#620)
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  data/profiles/minimal.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/M

#623 Ignore a warning in kubectl apply when namespace is already created.
  cmd/mesh/manifest.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#624 [release-1.4] Ignore a warning in kubectl apply when namespace is already created.
  cmd/mesh/manifest.go
Labels: cla: yes, size/S

#618 sync values types
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/L

#594 Remove original cr yaml from error message
  cmd/mesh/profile-dump.go
Labels: cla: yes, size/XS

#626 fix invalid image name.
  pkg/helmreconciler/rendering.go
Labels: cla: yes, size/XS

#625 Simplify and improve the user facing outputs.
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest.go
  pkg/manifest/installer.go
Labels: cherrypick/release-1.4, cla: yes, size/L

#627 [release-1.4] Simplify and improve the user facing outputs.
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest.go
  pkg/manifest/installer.go
Labels: cla: yes, size/L

#628 Clean up code
  cmd/mesh/manifest-common.go
  cmd/mesh/manifest-diff.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest-generate_test.go
  cmd/mesh/manifest.go
  cmd/mesh/profile-common.go
  cmd/mesh/profile-diff.go
  cmd/mesh/profile-dump.go
  cmd/mesh/upgrade.go
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/component/component/component.go
  pkg/component/feature/feature.go
  pkg/helm/helm.go
  pkg/helmreconciler/rendering.go
  pkg/name/name.go
  pkg/name/name_test.go
  pkg/object/objects.go
  pkg/object/objects_test.go
  pkg/tpath/tpath.go
  pkg/translate/translate.go
  pkg/translate/translate_value.go
  pkg/util/yaml.go
  pkg/version/version_test.go
Labels: cherrypick/release-1.4, cla: yes, size/XXL

#629 [release-1.4] Clean up code (#628)
  cmd/mesh/manifest-common.go
  cmd/mesh/manifest-diff.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest-generate_test.go
  cmd/mesh/manifest.go
  cmd/mesh/profile-common.go
  cmd/mesh/profile-diff.go
  cmd/mesh/profile-dump.go
  cmd/mesh/upgrade.go
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/component/component/component.go
  pkg/component/feature/feature.go
  pkg/helm/helm.go
  pkg/helmreconciler/rendering.go
  pkg/name/name.go
  pkg/name/name_test.go
  pkg/object/objects.go
  pkg/object/objects_test.go
  pkg/tpath/tpath.go
  pkg/translate/translate.go
  pkg/translate/translate_value.go
  pkg/util/yaml.go
  pkg/version/version_test.go
Labels: cla: yes, size/XXL

#631 Update installer and common files
  Makefile
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/report_build_info.sh
  installer.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/S

#633 Provide verbose output during test runs
  Makefile.core.mk
Labels: cla: yes, size/XS

#634 Update common files
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
  common/scripts/report_build_info.sh
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#640 Use RunE for cobra commands
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-diff.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest-migrate.go
  cmd/mesh/manifest-versions.go
  cmd/mesh/profile-diff.go
  cmd/mesh/profile-dump.go
  cmd/mesh/profile-list.go
  cmd/mesh/shared.go
Labels: cla: yes, size/L

#632 Remove unnecessary env variables
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  pkg/vfs/assets.gen.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#639 Add unit test and fix for ICP.DeepCopy()
  go.mod
  pkg/apis/istio/v1alpha2/deepcopy.go
  pkg/apis/istio/v1alpha2/deepcopy_test.go
Labels: cla: yes, ok-to-test, size/L

#642 [Release-1.4] Remove unnecessary env variables (#632)
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#641 Update CRDs in operator
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  deploy/clusterrole.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#644 Export methods for GenManifest and MakeTreeFromSetList
  cmd/mesh/manifest-common.go
  cmd/mesh/manifest-generate.go
Labels: cla: yes, size/S

#645 Export Logger and NewLogger
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-common.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest-generate_test.go
  cmd/mesh/manifest-migrate.go
  cmd/mesh/manifest-versions.go
  cmd/mesh/manifest-versions_test.go
  cmd/mesh/profile-common.go
  cmd/mesh/profile-dump.go
  cmd/mesh/root.go
  cmd/mesh/shared.go
  cmd/mesh/upgrade.go
Labels: cla: yes, size/M
