Repository istio/operator, pull requests merged in 2019-08, with the labels that each got.

#143 fix manifest diff for directory.
  cmd/mesh/manifest-diff.go
Labels: cla: yes, size/XS

#140 Update hub and tag to master
  data/charts/global.yaml
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
Labels: cla: yes, size/M

#145 Fix return code of manifest-diff
  cmd/mesh/manifest-diff.go
Labels: cla: yes, size/S

#147 add profile diff and list subcommand.
  cmd/mesh/profile-diff.go
  cmd/mesh/profile-list.go
  pkg/helm/vfs_renderer.go
  pkg/util/util.go
Labels: cla: yes, size/M

#144 Manifest versions command
  cmd/mesh/manifest-versions.go
  cmd/mesh/manifest.go
  cmd/mesh/root.go
  pkg/httprequest/httprequest.go
  version/version.go
  version/version.yaml
  version/version_test.go
Labels: cla: yes, size/L

#142 Create new translation mechanism, remove gateway lists support
  pkg/name/name.go
  pkg/patch/patch_test.go
  pkg/tpath/tpath.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
  pkg/util/path.go
Labels: cla: yes, size/XXL

#132 Add manifest migrate command
  cmd/mesh/manifest-diff.go
  cmd/mesh/manifest-migrate.go
  cmd/mesh/manifest.go
  pkg/kubectlcmd/client.go
  pkg/util/util.go
Labels: cla: yes, size/L

#152 Fix unwanted change during merge
  cmd/mesh/manifest-diff.go
Labels: cla: yes, size/S

#150 Add Morven to CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/XS

#151 Next generation building system
  Makefile
  Makefile.common.mk
  Makefile.container.mk
Labels: cla: yes, size/L

#154 sync chart.
  data/charts/crds/files/crd-10.yaml
  data/charts/crds/files/crd-12.yaml
  data/charts/crds/files/crd-certmanager-10.yaml
  data/charts/crds/files/crd-certmanager-11.yaml
  data/charts/crds/templates/crds.yaml
  data/charts/gateways/istio-ingress/templates/rolebindings.yaml
  data/charts/istio-control/istio-autoinject/files/injection-template.yaml
  data/charts/istio-control/istio-autoinject/templates/deployment.yaml
  data/charts/istio-control/istio-autoinject/templates/service.yaml
  data/charts/istio-control/istio-config/templates/configmap.yaml
  data/charts/istio-control/istio-config/templates/deployment.yaml
  data/charts/istio-control/istio-config/templates/service.yaml
  data/charts/istio-control/istio-config/templates/validatingwebhookconfiguration.yaml.tpl
  data/charts/istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
  data/charts/istio-telemetry/kiali/Chart.yaml
  data/charts/istio-telemetry/kiali/templates/clusterrole.yaml
  data/charts/istio-telemetry/kiali/templates/clusterrolebinding.yaml
  data/charts/istio-telemetry/kiali/templates/configmap.yaml
  data/charts/istio-telemetry/kiali/templates/deployment.yaml
  data/charts/istio-telemetry/kiali/values.yaml
  data/charts/security/citadel/templates/deployment.yaml
  data/charts/security/citadel/templates/service.yaml
  data/charts/security/nodeagent/templates/daemonset.yaml
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XL

#156 Use upstream gcr.io/istio-testing cononical image
  Makefile.common.mk
Labels: cla: yes, size/XS

#155 Get mac building working properly
  Makefile.common.mk
  Makefile.container.mk
Labels: cla: yes, size/S

#158 Unbreak docker build by using readlink
  Makefile.common.mk
Labels: cla: yes, size/XS

#159 Fix CODEOWNERS with a missing @
  CODEOWNERS
Labels: cla: yes, size/XS

#146 Update release version.
  release/update_version.sh
Labels: cla: yes, size/S

#163 Fix merge breakage
  data/charts/gateways/istio-ingress/templates/autoscale.yaml
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XL

#162 Fix mac building
  Makefile.common.mk
  Makefile.container.mk
  cmd/mesh.go
Labels: cla: yes, size/M

#167 fix linter issue of long line.
  pkg/name/name.go
  pkg/translate/translate.go
Labels: cla: yes, size/M

#165 refactor commands for istioctl integration
  cmd/mesh/manifest.go
  cmd/mesh/profile.go
  cmd/mesh/root.go
  go.mod
  go.sum
Labels: cla: yes, size/L

#149 Fixes for issues discovered during demo
  cmd/mesh/manifest-apply.go
  data/charts/crds/templates/crds.yaml
  data/charts/global.yaml
  data/charts/istiocoredns/Chart.yaml
  data/charts/istiocoredns/templates/_affinity.tpl
  data/charts/istiocoredns/templates/clusterrole.yaml
  data/charts/istiocoredns/templates/clusterrolebinding.yaml
  data/charts/istiocoredns/templates/configmap.yaml
  data/charts/istiocoredns/templates/deployment.yaml
  data/charts/istiocoredns/templates/service.yaml
  data/charts/istiocoredns/templates/serviceaccount.yaml
  data/charts/istiocoredns/values.yaml
  pkg/vfsgen/vfsgen_data.go
  samples/demo.yaml
  samples/pilot-values.yaml
  samples/sds-custom1.yaml
  scripts/run_mandiff.sh
  scripts/sync_charts.sh
  tests/profiles/helm/values-istio-default.yaml
  tests/profiles/helm/values-istio-demo-auth.yaml
  tests/profiles/helm/values-istio-demo.yaml
  tests/profiles/helm/values-istio-minimal.yaml
  tests/profiles/helm/values-istio-sds.yaml
Labels: cla: yes, size/XL

#161 Prom fix
  cmd/mesh.go
  data/charts/crds/files/crd-11.yaml
  data/charts/crds/templates/namespaces.yaml
  data/charts/global.yaml
  data/charts/istio-control/istio-autoinject/files/injection-template.yaml
  data/charts/istio-control/istio-autoinject/templates/clusterrole.yaml
  data/charts/istio-control/istio-autoinject/templates/deployment.yaml
  data/charts/istio-control/istio-autoinject/templates/mutatingwebhook.yaml
  data/charts/istio-control/istio-config/templates/deployment.yaml
  data/charts/istio-control/istio-discovery/templates/autoscale.yaml
  data/charts/istio-control/istio-discovery/templates/clusterrole.yaml
  data/charts/istio-control/istio-discovery/templates/clusterrolebinding.yaml
  data/charts/istio-control/istio-discovery/templates/configmap-envoy.yaml
  data/charts/istio-control/istio-discovery/templates/configmap.yaml
  data/charts/istio-control/istio-discovery/templates/deployment.yaml
  data/charts/istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
  data/charts/istio-control/istio-discovery/templates/poddisruptionbudget.yaml
  data/charts/istio-control/istio-discovery/templates/service.yaml
  data/charts/istio-control/istio-discovery/templates/serviceaccount.yaml
  data/charts/istio-telemetry/mixer-telemetry/templates/config-stdio.yaml
  data/charts/istio-telemetry/mixer-telemetry/templates/config.yaml
  data/charts/istio-telemetry/mixer-telemetry/templates/deployment.yaml
  data/charts/security/citadel/templates/clusterrole.yaml
  data/charts/security/citadel/templates/clusterrolebinding.yaml
  data/charts/security/citadel/templates/deployment.yaml
  data/charts/security/citadel/templates/poddisruptionbudget.yaml
  data/charts/security/citadel/templates/serviceaccount.yaml
  data/charts/security/nodeagent/templates/serviceaccount.yaml
  data/profiles/default.yaml
  go.mod
  go.sum
  pkg/component/component/component.go
  pkg/component/controlplane/control_plane_test.go
  pkg/component/feature/feature.go
  pkg/helm/fs_renderer.go
  pkg/helm/helm.go
  pkg/helm/vfs_renderer.go
  pkg/name/name.go
  pkg/object/objects.go
  pkg/translate/translate.go
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XXL

#168 This is unneeded and probably incorrect.
  Makefile.core.mk
Labels: cla: yes, size/XS

#173 Fixes to converge to installer charts
  data/charts/istio-control/istio-autoinject/templates/configmap.yaml
  data/profiles/default.yaml
  pkg/component/controlplane/control_plane_test.go
  pkg/component/controlplane/testdata/pilot_default.yaml
  pkg/component/controlplane/testdata/pilot_override_kubernetes.yaml
  pkg/component/controlplane/testdata/pilot_override_values.yaml
  pkg/name/name.go
  pkg/object/objects.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/vfsgen/vfsgen_data.go
  scripts/run_mandiff.sh
  tests/profiles/mesh/default-profile.yaml
  tests/profiles/mesh/demo-auth-profile.yaml
  tests/profiles/mesh/demo-profile.yaml
  tests/profiles/mesh/minimal-profile.yaml
  tests/profiles/mesh/sds-profile.yaml
Labels: cla: yes, size/L

#174 Relative profiles
  .commonfiles.sha
  Makefile
  cmd/mesh/manifest.go
  cmd/mesh/profile-dump.go
  data/profiles/demo.yaml
  pkg/helm/helm.go
  pkg/vfsgen/vfsgen.go
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XL

#172 Update the commonfiles and and update vfsgen
  .commonfiles.sha
  cmd/mesh.go
  pkg/vfsgen/vfsgen.gen.go
  pkg/vfsgen/vfsgen.go
Labels: cla: yes, size/XL

#171 tune profiles to fix gaps.
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
  pkg/vfsgen/vfsgen.gen.go
Labels: cla: yes, size/XXL

#176 Fix make mesh breakage
  Makefile.core.mk
  cmd/vfsgen/vfsgen.go
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XL

#177 Update README
  README.md
  samples/customize_pilot.yaml
  samples/pilot-advanced-override.yaml
  samples/pilot-k8s.yaml
  samples/pilot-values.yaml
  samples/sds-policy-off.yaml
  samples/sds.yaml
  samples/trafficManagement-namespace.yaml
  samples/values-global.yaml
  samples/values-pilot.yaml
Labels: cla: yes, size/L

#179 Update makefile for GOBIN
  Makefile.core.mk
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XL

#170 fix namespace gaps for mandiff.
  data/charts/global.yaml
  data/profiles/default.yaml
  pkg/vfsgen/vfsgen_data.go
  scripts/run_mandiff.sh
  tests/profiles/helm/values-istio-default.yaml
  tests/profiles/helm/values-istio-demo-auth.yaml
  tests/profiles/helm/values-istio-demo.yaml
  tests/profiles/helm/values-istio-minimal.yaml
  tests/profiles/helm/values-istio-sds.yaml
Labels: cla: yes, size/XL

#153 conditionize initing features and components.
  data/profiles/default.yaml
  data/profiles/sds.yaml
  pkg/component/component/component.go
  pkg/component/controlplane/control_plane.go
  pkg/component/feature/feature.go
  pkg/name/name.go
  pkg/translate/translate.go
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/L

#141 Release script
  release/create_release_charts.sh
Labels: cla: yes, size/M

#183 Fix for vfsgen reader
  data/charts/istio-telemetry/mixer-telemetry/templates/config-stdio.yaml
  data/charts/istio-telemetry/mixer-telemetry/templates/config.yaml
  pkg/vfsgen/vfsgen.go
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XL

#184 Fix comment
  pkg/name/name.go
Labels: cla: yes, size/XS

#181 add select and ignore flags for manifest diff command.
  cmd/mesh/manifest-diff.go
  pkg/object/objects.go
  pkg/object/objects_test.go
Labels: cla: yes, size/XL

#187 add readable ut.
  pkg/object/objects_test.go
Labels: cla: yes, size/L

#189 Set release managers as CODEOWNERS for release-1.3
  CODEOWNERS
Labels: area/test and release, cla: yes, size/XS

#180 Eliminate use of vfsgen
  Makefile.core.mk
  cmd/mesh.go
  cmd/vfsgen/vfsgen.go
  pkg/helm/vfs_renderer.go
  pkg/vfs/assets.gen.go
  pkg/vfs/vfs.go
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XXL

#186 Add support for installation from url
  cmd/mesh/manifest.go
  pkg/helm/testdata/istio-installer-1.3.0.tar.gz
  pkg/helm/testdata/istio-installer-1.3.0.tar.gz.sha256
  pkg/helm/urlfetcher.go
  pkg/helm/urlfetcher_test.go
  pkg/helm/urlwatcher.go
  pkg/util/common.go
  pkg/version/version.go
Labels: cla: yes, size/L

#192 fix crds chart directory.
  scripts/run_update_charts.sh
Labels: cla: yes, size/XS

#194 k8s resource limits cannot be lower than requests
  data/profiles/default.yaml
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XL

#193 fix mandiff gaps
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  scripts/run_mandiff.sh
Labels: cla: yes, size/M

#178 Update the README file
  README.md
Labels: cla: yes, size/XS

#195 Modify output path for charts
  release/create_release_charts.sh
Labels: cla: yes, size/XS

#197 Set dry run default to false
  cmd/mesh/root.go
Labels: cla: yes, size/XS

#196 Fix update chart script
  pkg/vfsgen/vfsgen_data.go
  scripts/run_update_charts.sh
Labels: cla: yes, size/XL

#198 Fix translate and profile issues
  data/profiles/default.yaml
  pkg/translate/translate_value.go
Labels: cla: yes, size/S

#201 fix broken manifest generating and mandiff.
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/sds.yaml
  pkg/translate/translate.go
  pkg/vfsgen/vfsgen_data.go
  scripts/run_mandiff.sh
Labels: cla: yes, size/XL

#200 Eliminate vfsgen again.
  Makefile.core.mk
  README.md
  cmd/mesh.go
  cmd/vfsgen/vfsgen.go
  go.mod
  go.sum
  pkg/helm/vfs_renderer.go
  pkg/vfs/assets.gen.go
  pkg/vfs/vfs.go
  pkg/vfsgen/vfsgen_data.go
Labels: cla: yes, size/XXL

#202 Fix build commmand for installing go-bindata
  README.md
Labels: cla: yes, size/S

#169 Update makefile for proto related rules
  Makefile.core.mk
  pkg/apis/istio/v1alpha2/README.md
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/values/values_types.pb.go
Labels: cla: yes, size/XXL

#203 Merge two install sections into one
  README.md
Labels: cla: yes, size/S

#207 Update to 2019-08-16 commonfiles
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.overrides.mk
  SUPPORT.md
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#206 support resource type for k8s mapping.
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/sds.yaml
  pkg/translate/translate.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XL

#205 Fix reverse translation issue
  cmd/mesh/manifest-migrate.go
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
Labels: cla: yes, size/L

#208 Fix flag not taking effect in manifest generate.
  cmd/mesh/manifest.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: cla: yes, size/L

#213 [release-1.3] Fix flag not taking effect in manifest generate.
  cmd/mesh/manifest.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: cla: yes, size/L

#210 Changes to API for mesh config integration
  README.md
  cmd/mesh/manifest.go
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
  go.mod
  go.sum
  installer.sha
  pkg/apis/istio/v1alpha2/fixup_go_structs.patch
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/component/component/component.go
  pkg/component/controlplane/control_plane_test.go
  pkg/component/controlplane/testdata/pilot_k8s_settings.yaml
  pkg/name/name.go
  pkg/object/objects_test.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
  pkg/validate/validate_test.go
  pkg/vfs/assets.gen.go
  samples/pilot-advanced-override.yaml
  samples/pilot-k8s.yaml
  samples/values-pilot.yaml
  scripts/run_mandiff.sh
Labels: cla: yes, size/XXL

#212 update doc.
  ARCHITECTURE.md
  README.md
Labels: cla: yes, size/M

#214 Clean up values
  data/profiles/demo-auth.yaml
Labels: cla: yes, size/XS

#217 remove invalid and duplicated fields.
  data/profiles/default.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#215 update reverse logic after api changes
  pkg/translate/translate.go
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
  scripts/run_mandiff.sh
Labels: cla: yes, size/M

#221 Cherrypicks from master
  .commonfiles.sha
  ARCHITECTURE.md
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  Makefile.overrides.mk
  README.md
  SUPPORT.md
  cmd/mesh.go
  cmd/mesh/manifest-migrate.go
  cmd/vfsgen/vfsgen.go
  data/profiles/default.yaml
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/minimal.yaml
  data/profiles/sds.yaml
  go.mod
  go.sum
  pkg/apis/istio/v1alpha2/README.md
  pkg/apis/istio/v1alpha2/fixup_go_structs.patch
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/values/values_types.pb.go
  pkg/component/component/component.go
  pkg/component/controlplane/control_plane_test.go
  pkg/component/controlplane/testdata/pilot_k8s_settings.yaml
  pkg/helm/vfs_renderer.go
  pkg/name/name.go
  pkg/object/objects_test.go
  pkg/translate/translate.go
  pkg/translate/translate_test.go
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
  pkg/validate/validate_test.go
  pkg/vfs/assets.gen.go
  pkg/vfs/vfs.go
  pkg/vfsgen/vfsgen_data.go
  samples/pilot-advanced-override.yaml
  samples/pilot-k8s.yaml
  samples/values-pilot.yaml
  scripts/run_mandiff.sh
Labels: cla: yes, size/XXL

#216 Use release-1.3 tag for release-1.3 branch
  ARCHITECTURE.md
  README.md
  data/profiles/default.yaml
  pkg/component/controlplane/testdata/charts/istio-cni/values.yaml
Labels: cla: yes, size/M

#222 fix mandiff gaps.
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/sds.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XXL

#86 Dynamic validation
  pkg/apis/istio/v1alpha2/validation/validation.go
  pkg/apis/istio/v1alpha2/validation/validation_test.go
  pkg/apis/istio/v1alpha2/values_types.go
Labels: cla: yes, size/L

#223 add back the mandiff test.
  Makefile.core.mk
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  data/profiles/sds.yaml
  installer.sha
  pkg/vfs/assets.gen.go
  scripts/run_mandiff.sh
Labels: cla: yes, size/XXL

#224 merge mandiff gaps fix.
  Makefile.core.mk
  data/profiles/demo-auth.yaml
  data/profiles/demo.yaml
  data/profiles/sds.yaml
  installer.sha
  pkg/vfs/assets.gen.go
  scripts/run_mandiff.sh
Labels: cla: yes, size/XXL

#225 Improve mandiff: ignore specified paths inside manifests. Add yaml compare tool to only output diff with neat paths
  go.mod
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/object/objects.go
  scripts/run_mandiff.sh
Labels: cla: yes, size/XL

#229 Update common files.
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/report_build_info.sh
Labels: cla: yes, size/L

#236 Updates to mesh command help text
  cmd/mesh/manifest-apply.go
  cmd/mesh/manifest-diff.go
  cmd/mesh/manifest-generate.go
  cmd/mesh/manifest-migrate.go
  cmd/mesh/manifest.go
  cmd/mesh/profile-diff.go
  cmd/mesh/profile-dump.go
  cmd/mesh/profile-list.go
  cmd/mesh/profile.go
Labels: cla: yes, size/S

#241 Revert go-bindata due to release build issues
  Makefile.core.mk
  cmd/mesh/manifest-apply.go
  cmd/mesh/shared.go
  cmd/vfsgen/vfsgen.go
  go.mod
  go.sum
  pkg/vfs/assets.gen.go
  pkg/vfs/vfs.go
Labels: cla: yes, size/XXL

#239 Cleanup values_types.proto
  Makefile.core.mk
  pkg/apis/istio/v1alpha2/values/fix_values_structs.patch
  pkg/apis/istio/v1alpha2/values/fixup_structs/main.go
  pkg/apis/istio/v1alpha2/values/values.pb.html
  pkg/apis/istio/v1alpha2/values/values_types.pb.go
  pkg/apis/istio/v1alpha2/values/values_types.proto
  python/istio_api/pkg/apis/istio/v1alpha2/values/values_types_pb2.py
Labels: cla: yes, size/XXL
