Repository istio/operator, pull requests merged in 2020-01, with the labels that each got.

#730 Sync installer SHA
  cmd/mesh/testdata/manifest-generate/output/all_off.yaml
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_force.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_default.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  data/profiles/demo.yaml
  installer.sha
  pkg/vfs/assets.gen.go
  tests/e2e/e2e.sh
  tests/profiles/helm/values-istio-demo.yaml
Labels: cla: yes, size/XXL

#729 update translate config
  data/translateConfig/reverseTranslateConfig-1.4.yaml
  data/translateConfig/reverseTranslateConfig-1.5.yaml
  data/translateConfig/translateConfig-1.5.yaml
  pkg/translate/translate_test.go
  pkg/translate/translate_value.go
  pkg/translate/translate_value_test.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/L

#732 Set CNI namespace as kube-system by default
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  pkg/translate/translate_test.go
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/M

#731 Set SilenceUsage true to mesh command
  cmd/mesh/root.go
Labels: cla: yes, ok-to-test, size/XS

#734 Fix pilot readiness probe
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#735 add issue link to the ObjectMeta marshalling.
  cmd/mesh/manifest-migrate.go
  cmd/mesh/manifest-migrate_test.go
Labels: cla: yes, size/XS

#737 remove file watcher for template renderer
  pkg/helm/fs_renderer.go
Labels: cla: yes, size/S

#736 add serviceAnnotation to KubernetesResourcesSpec.
  ARCHITECTURE.md
  cmd/mesh/testdata/manifest-generate/input/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-migrate/output/default_values.yaml
  data/translateConfig/reverseTranslateConfig-1.5.yaml
  data/translateConfig/translateConfig-1.5.yaml
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go
  pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
  pkg/apis/istio/v1alpha2/v1alpha2.pb.html
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha2/istiocontrolplane_types_pb2.py
Labels: cla: yes, size/S

#738 Add various of tag format support in version check of istioctl upgrade
  cmd/mesh/upgrade.go
  pkg/manifest/client.go
  pkg/version/version.go
  pkg/version/version_test.go
  version/version.go
Labels: cla: yes, size/L

#741 fix iop status update issue.
  deploy/crds/istio_v1alpha2_istiooperator_crd.yaml
  go.mod
  go.sum
  pkg/apis/addtoscheme_istio_v1alpha1.go
  pkg/apis/istio/v1alpha1/operator_crd.pb.go
  pkg/apis/istio/v1alpha1/register.go
  pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go
  pkg/controller/istiocontrolplane/listeners.go
  pkg/helmreconciler/interfaces.go
  pkg/helmreconciler/listeners.go
  pkg/helmreconciler/reconciler.go
  pkg/util/common.go
Labels: cla: yes, size/L

#744 remove dynamic rest mapper from openshift.
  cmd/manager/server.go
  go.mod
  go.sum
  licenses/github.com/openshift/api/LICENSE
  licenses/github.com/openshift/cluster-network-operator/LICENSE
  licenses/k8s.io/kube-proxy/LICENSE
Labels: cla: yes, size/XL

#740 add serviceAnnotation to KubernetesResourcesSpec.
  cmd/mesh/testdata/manifest-generate/input/telemetry_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/telemetry_k8s_settings.yaml
  data/translateConfig/translateConfig-1.5.yaml
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#742 fix dry-run error
  cmd/mesh/manifest-apply.go
  pkg/manifest/installer.go
Labels: cla: yes, size/XS

#751 repalce remaining istio operator api version.
  cmd/mesh/testdata/operator/output/operator-init.yaml
  cmd/mesh/testdata/operator/output/operator-remove.yaml
  data/operator/templates/crd.yaml
  deploy/crds/istio_v1alpha1_istiooperator_cr.yaml
  deploy/crds/istio_v1alpha1_istiooperator_crd.yaml
  deploy/kustomization.yaml
  pkg/apis/istio/v1alpha1/doc.go
  pkg/apis/istio/v1alpha1/register.go
  pkg/controller/istiocontrolplane/inputs.go
  pkg/name/name.go
  pkg/vfs/assets.gen.go
  tests/e2e/e2e.sh
Labels: cla: yes, size/S

#750 move operator api GVK to api package.
  pkg/apis/istio/v1alpha1/register.go
  pkg/controller/istiocontrolplane/pruningdetails.go
  pkg/helmreconciler/listeners.go
  pkg/util/common.go
Labels: cla: yes, size/S

#749 only prune the managed resources.
  pkg/controller/istiocontrolplane/pruningdetails.go
  pkg/helmreconciler/customizers.go
  pkg/helmreconciler/interfaces.go
  pkg/helmreconciler/pruning.go
  pkg/helmreconciler/rendering.go
Labels: cla: yes, size/L

#747 Update the binary version to 1.4.4
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_default.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.yaml
  cmd/mesh/testdata/manifest-generate/output/pilot_override_values.yaml
  data/versions.yaml
  installer.sha
  pkg/vfs/assets.gen.go
  version/version.go
Labels: cla: yes, size/L

#752 Close repo message
  README.md
Labels: cla: yes, size/XS

#754 [release-1.3] Update installer SHA
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/S

#756 Update installer SHA
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS
