Repository istio/operator, pull requests merged in 2020-02, with the labels that each got.

#758 [release-1.4] Updating operator repo with new cni stuff
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  installer.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/L

#760 Updating installer sha
  installer.sha
Labels: cla: yes, size/XS

#761 Adding updated generated assets file
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#763 Updating installer SHA
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/XS

#762 Backporting istio/istio PR#20897 to 1.4-release
  pkg/object/objects.go
Labels: cla: yes, size/XS

#765 sync installer to 229017cf98e3fac0be42f0ebec277abd3b04e774
  cmd/mesh/testdata/manifest-generate/output/all_on.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_output_set_values.yaml
  cmd/mesh/testdata/manifest-generate/output/flag_set_values.yaml
  installer.sha
  pkg/vfs/assets.gen.go
Labels: cla: yes, size/M

#766 Manual cherrypick of (istio/istio#20923)
  installer.sha
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/XS

#757 [release-1.4] Add stackdriver tracer to operator
  cmd/mesh/testdata/profile-dump/output/all_off.yaml
  cmd/mesh/testdata/profile-dump/output/sds_policy_off.yaml
  data/profiles/default.yaml
  pkg/apis/istio/v1alpha1/v1alpha1.pb.html
  pkg/apis/istio/v1alpha1/values_types.pb.go
  pkg/apis/istio/v1alpha1/values_types.proto
  pkg/vfs/assets.gen.go
  python/istio_api/pkg/apis/istio/v1alpha1/values_types_pb2.py
Labels: cla: yes, size/M
